Pinhao: pinhao::IfFormula< T > Class Template Reference
pinhao::IfFormula< T > Class Template Reference
The If Formula.
#include <IfFormula.h>
Public Member Functions
ValueType getType () const override
Gets the type of the Formula (what is the returning type).
FormulaKind getKind () const override
Gets a FormulaKind of this object.
void evolve (Evolution *) override
Evolves this formula, based on the Evolution algorithm.
FormulaBase * simplify () override
Simplifies the current formula.
void generate (FeatureSet *Set) override
Randomizes the generations of a Formula.
void solveFor (FeatureSet *Set) override
Evaluates the Formula for the Set.
bool operator== (const FormulaBase &Rhs) const override
bool operator< (const FormulaBase &Rhs) const override
std::unique_ptr< FormulaBase > clone () override
Clones (deep copy) the formula.
Public Member Functions inherited from pinhao::Formula< T >
virtual ~Formula ()
T & getValue ()
Gets a reference to the value.
T getValue () const
Gets a copy of the value.
virtual ValueType getOperandsType () const
Return the type of the operands. If it has none, it returns the type of the Formula.
Public Member Functions inherited from pinhao::FormulaBase
virtual ~FormulaBase ()
virtual bool isLiteral () const
Returns true if it is a Literal formula.
virtual bool isArithBinOp () const
Returns true if it is a ArithBinOp formula.
virtual bool isBoolBinOp () const
Returns true if it is a BoolBinOp formula.
virtual bool isFeature () const
Returns true if it is a Feature formula.
virtual bool isIf () const
Returns true if it is a If formula.
bool operator!= (const FormulaBase &Rhs) const
bool operator> (const FormulaBase &Rhs) const
bool operator>= (const FormulaBase &Rhs) const
bool operator<= (const FormulaBase &Rhs) const
void print (std::ostream &Out=std::cout)
Prints to an std::ostream object the information of this Formula.
Public Attributes
std::unique_ptr< FormulaBase > Condition
std::unique_ptr< FormulaBase > ThenBody
std::unique_ptr< FormulaBase > ElseBody
Additional Inherited Members
Static Protected Member Functions inherited from pinhao::Formula< T >
static T getFormulaValue (const FormulaBase *Base)
A wrapper that gets the value yielded.
Protected Attributes inherited from pinhao::Formula< T >
T Value
The value that is yielded after evaluation.
Detailed Description
template<class T>
class pinhao::IfFormula< T >
The If Formula.
It evaluates the Condition, which if true, returns the value yielded by the ThenBody Formula. Else, returns the value of the ElseBody Formula.
Definition at line 22 of file IfFormula.h.
Member Function Documentation
template<class T > std::unique_ptr< pinhao::FormulaBase > pinhao::IfFormula< T >::clone () override virtual
Clones (deep copy) the formula.
Implements pinhao::FormulaBase.
Definition at line 120 of file IfFormula.h.
References pinhao::IfFormula< T >::Condition, pinhao::IfFormula< T >::ElseBody, and pinhao::IfFormula< T >::ThenBody.
template<class T > void pinhao::IfFormula< T >::evolve (Evolution *) override virtual
Evolves this formula, based on the Evolution algorithm.
Implements pinhao::FormulaBase.
Definition at line 56 of file IfFormula.h.
References pinhao::IfFormula< T >::Condition, pinhao::IfFormula< T >::ElseBody, pinhao::Evolution::evolve(), and pinhao::IfFormula< T >::ThenBody.
template<class T > void pinhao::IfFormula< T >::generate (FeatureSet * Set) override virtual
Randomizes the generations of a Formula.
Implements pinhao::FormulaBase.
Definition at line 74 of file IfFormula.h.
References pinhao::Bool, pinhao::IfFormula< T >::Condition, pinhao::IfFormula< T >::ElseBody, pinhao::generateFormula(), and pinhao::IfFormula< T >::ThenBody.
template<class T > pinhao::FormulaKind pinhao::IfFormula< T >::getKind () const override virtual
Gets a FormulaKind of this object.
Implements pinhao::FormulaBase.
Definition at line 51 of file IfFormula.h.
References pinhao::If.
template<class T > pinhao::ValueType pinhao::IfFormula< T >::getType () const override virtual
Gets the type of the Formula (what is the returning type).
Implements pinhao::FormulaBase.
Definition at line 46 of file IfFormula.h.
template<class T > bool pinhao::IfFormula< T >::operator< (const FormulaBase & Rhs) const override virtual
Implements pinhao::FormulaBase.
Definition at line 103 of file IfFormula.h.
References pinhao::IfFormula< T >::Condition, pinhao::IfFormula< T >::ElseBody, pinhao::IfFormula< T >::getKind(), pinhao::FormulaBase::getKind(), pinhao::IfFormula< T >::getType(), pinhao::FormulaBase::getType(), and pinhao::IfFormula< T >::ThenBody.
template<class T > bool pinhao::IfFormula< T >::operator== (const FormulaBase & Rhs) const override virtual
Implements pinhao::FormulaBase.
Definition at line 93 of file IfFormula.h.
References pinhao::IfFormula< T >::Condition, pinhao::IfFormula< T >::ElseBody, pinhao::IfFormula< T >::getKind(), pinhao::FormulaBase::getKind(), pinhao::IfFormula< T >::getType(), pinhao::FormulaBase::getType(), and pinhao::IfFormula< T >::ThenBody.
template<class T > pinhao::FormulaBase * pinhao::IfFormula< T >::simplify () override virtual
Simplifies the current formula.
Implements pinhao::FormulaBase.
Definition at line 61 of file IfFormula.h.
References pinhao::IfFormula< T >::Condition, pinhao::IfFormula< T >::ElseBody, pinhao::simplifyFormula(), and pinhao::IfFormula< T >::ThenBody.
template<class T > void pinhao::IfFormula< T >::solveFor (FeatureSet * Set) override virtual
Evaluates the Formula for the Set.
Implements pinhao::FormulaBase.
Definition at line 81 of file IfFormula.h.
References pinhao::IfFormula< T >::Condition, pinhao::IfFormula< T >::ElseBody, pinhao::IfFormula< T >::ThenBody, and pinhao::Formula< T >::Value.
Member Data Documentation
template<class T> std::unique_ptr<FormulaBase> pinhao::IfFormula< T >::Condition
Definition at line 24 of file IfFormula.h.
template<class T> std::unique_ptr<FormulaBase> pinhao::IfFormula< T >::ElseBody
Definition at line 26 of file IfFormula.h.
template<class T> std::unique_ptr<FormulaBase> pinhao::IfFormula< T >::ThenBody
Definition at line 25 of file IfFormula.h.