Pinhao: pinhao::OptimizationInfo Class Reference
pinhao::OptimizationInfo Class Reference
Has the information (the arguments) of each optimization.
#include <OptimizationInfo.h>
Public Types
typedef std::vector< OptimizationArgBase * >::iterator ArgsIterator
Public Member Functions
~OptimizationInfo ()
OptimizationInfo ()
OptimizationInfo (Optimization Opt)
OptimizationInfo (std::string OptName)
OptimizationInfo (const OptimizationInfo &Info)
std::string getName () const
Gets the name of the optimization.
Optimization getOptimization () const
Gets the optimization.
llvm::Pass * createPass ()
Creates a llvm::Pass corresponding to this optimization.
const OptimizationArgBase * getOptimizationArg (uint64_t N) const
Gets a the Nth OptimizationArg.
template<class ArgType >
void setArg (int N, ArgType Value) const
Sets the Nth argument to Value.
template<class ArgType >
ArgType getArg (uint64_t N) const
Gets the Nth argument.
ValueType getArgType (uint64_t N) const
Gets the type of the Nth argument.
uint64_t getNumberOfArguments () const
Gets the number of arguments.
OptimizationInfo & operator= (const OptimizationInfo &Info)
Copy assignment operator.
ArgsIterator begin ()
ArgsIterator end ()
Private Member Functions
void copy (const OptimizationInfo &Info)
Copies the content of Info to this object.
Private Attributes
Optimization Opt
std::vector< OptimizationArgBase * > Args
The arguments of this optimization.
Detailed Description
Has the information (the arguments) of each optimization.
Definition at line 37 of file OptimizationInfo.h.
Member Typedef Documentation
typedef std::vector<OptimizationArgBase*>::iterator pinhao::OptimizationInfo::ArgsIterator
Definition at line 90 of file OptimizationInfo.h.
Constructor & Destructor Documentation
OptimizationInfo::~OptimizationInfo ()
Definition at line 44 of file OptimizationInfo.cpp.
References Args.
OptimizationInfo::OptimizationInfo ()
Definition at line 49 of file OptimizationInfo.cpp.
OptimizationInfo::OptimizationInfo (Optimization Opt)
Definition at line 58 of file OptimizationInfo.cpp.
References Args, pinhao::Bool, pinhao::gvn, pinhao::Int, pinhao::jumpThreading, pinhao::loopRotate, pinhao::loopUnroll, pinhao::loopUnswitch, pinhao::scalarrepl, and pinhao::simplifycfg.
OptimizationInfo::OptimizationInfo (std::string OptName)
Definition at line 53 of file OptimizationInfo.cpp.
OptimizationInfo::OptimizationInfo (const OptimizationInfo & Info)
Definition at line 103 of file OptimizationInfo.cpp.
References copy().
Member Function Documentation
ArgsIterator pinhao::OptimizationInfo::begin () inline
Definition at line 91 of file OptimizationInfo.h.
void OptimizationInfo::copy (const OptimizationInfo & Info) private
Copies the content of Info to this object.
Definition at line 21 of file OptimizationInfo.cpp.
References Args, pinhao::Bool, pinhao::Float, getArg(), getArgType(), getNumberOfArguments(), pinhao::Int, Opt, and pinhao::String.
llvm::Pass * OptimizationInfo::createPass ()
Creates a llvm::Pass corresponding to this optimization.
Definition at line 125 of file OptimizationInfo.cpp.
References getName(), pinhao::gvn, pinhao::jumpThreading, pinhao::loopRotate, pinhao::loopUnroll, pinhao::loopUnswitch, Opt, pinhao::scalarrepl, and pinhao::simplifycfg.
ArgsIterator pinhao::OptimizationInfo::end () inline
Definition at line 92 of file OptimizationInfo.h.
template<class ArgType > ArgType pinhao::OptimizationInfo::getArg (uint64_t N) const inline
Gets the Nth argument.
Definition at line 75 of file OptimizationInfo.h.
References pinhao::OptimizationArg< ArgType >::Value.
ValueType OptimizationInfo::getArgType (uint64_t N) const
Gets the type of the Nth argument.
Definition at line 162 of file OptimizationInfo.cpp.
References Args.
std::string OptimizationInfo::getName () const
Gets the name of the optimization.
Definition at line 117 of file OptimizationInfo.cpp.
References pinhao::getOptimizationName(), and Opt.
uint64_t OptimizationInfo::getNumberOfArguments () const
Gets the number of arguments.
Definition at line 167 of file OptimizationInfo.cpp.
References Args.
Optimization OptimizationInfo::getOptimization () const
Gets the optimization.
Definition at line 121 of file OptimizationInfo.cpp.
References Opt.
const OptimizationArgBase * OptimizationInfo::getOptimizationArg (uint64_t N) const
Gets a the Nth OptimizationArg.
Definition at line 112 of file OptimizationInfo.cpp.
References Args.
OptimizationInfo & OptimizationInfo::operator= (const OptimizationInfo & Info)
Copy assignment operator.
Definition at line 107 of file OptimizationInfo.cpp.
References copy().
template<class ArgType > void pinhao::OptimizationInfo::setArg (int N, ArgType Value) const inline
Sets the Nth argument to Value.
Definition at line 67 of file OptimizationInfo.h.
References pinhao::OptimizationArg< ArgType >::Value.
Member Data Documentation
std::vector<OptimizationArgBase*> pinhao::OptimizationInfo::Args private
The arguments of this optimization.
Definition at line 42 of file OptimizationInfo.h.
Optimization pinhao::OptimizationInfo::Opt private
Definition at line 39 of file OptimizationInfo.h.