Pinhao: pinhao::FormulaBase Class Reference
pinhao::FormulaBase Class Reference abstract
The base class for all Formula types. A Formula is a statement which when evaluated for a FeatureSet, it yields a value.
#include <Formula.h>
Public Member Functions
virtual ~FormulaBase ()
virtual ValueType getType () const =0
Gets the type of the Formula (what is the returning type).
virtual FormulaKind getKind () const =0
Gets a FormulaKind of this object.
virtual bool isLiteral () const
Returns true if it is a Literal formula.
virtual bool isArithBinOp () const
Returns true if it is a ArithBinOp formula.
virtual bool isBoolBinOp () const
Returns true if it is a BoolBinOp formula.
virtual bool isFeature () const
Returns true if it is a Feature formula.
virtual bool isIf () const
Returns true if it is a If formula.
virtual void evolve (Evolution *)=0
Evolves this formula, based on the Evolution algorithm.
virtual FormulaBase * simplify ()=0
Simplifies the current formula.
virtual void generate (FeatureSet *Set)=0
Randomizes the generations of a Formula.
virtual void solveFor (FeatureSet *Set)=0
Evaluates the Formula for the Set.
bool operator!= (const FormulaBase &Rhs) const
bool operator> (const FormulaBase &Rhs) const
bool operator>= (const FormulaBase &Rhs) const
bool operator<= (const FormulaBase &Rhs) const
virtual bool operator== (const FormulaBase &Rhs) const =0
virtual bool operator< (const FormulaBase &Rhs) const =0
void print (std::ostream &Out=std::cout)
Prints to an std::ostream object the information of this Formula.
virtual std::unique_ptr< FormulaBase > clone ()=0
Clones (deep copy) the formula.
Detailed Description
The base class for all Formula types. A Formula is a statement which when evaluated for a FeatureSet, it yields a value.
Definition at line 95 of file Formula.h.
Constructor & Destructor Documentation
virtual pinhao::FormulaBase::~FormulaBase () inline virtual
Definition at line 97 of file Formula.h.
Member Function Documentation
virtual std::unique_ptr<FormulaBase> pinhao::FormulaBase::clone () pure virtual
Clones (deep copy) the formula.
Implemented in pinhao::BinOpFormulaBase< T, OpT >, pinhao::BinOpFormulaBase< bool, T >, pinhao::BinOpFormulaBase< T, T >, pinhao::BinOpFormulaBase< bool, bool >, pinhao::LitFormula< T >, pinhao::IfFormula< T >, and pinhao::FeatureFormula< T >.
virtual void pinhao::FormulaBase::evolve (Evolution *) pure virtual
Evolves this formula, based on the Evolution algorithm.
Implemented in pinhao::BinOpFormulaBase< T, OpT >, pinhao::BinOpFormulaBase< bool, T >, pinhao::BinOpFormulaBase< T, T >, pinhao::BinOpFormulaBase< bool, bool >, pinhao::LitFormula< T >, pinhao::IfFormula< T >, and pinhao::FeatureFormula< T >.
virtual void pinhao::FormulaBase::generate (FeatureSet * Set) pure virtual
Randomizes the generations of a Formula.
Implemented in pinhao::BinOpFormulaBase< T, OpT >, pinhao::BinOpFormulaBase< bool, T >, pinhao::BinOpFormulaBase< T, T >, pinhao::BinOpFormulaBase< bool, bool >, pinhao::LitFormula< T >, pinhao::IfFormula< T >, and pinhao::FeatureFormula< T >.
virtual FormulaKind pinhao::FormulaBase::getKind () const pure virtual
Gets a FormulaKind of this object.
Implemented in pinhao::BoolBinOpFormula< bool >, pinhao::BoolBinOpFormula< T >, pinhao::ArithBinOpFormula< T >, pinhao::LitFormula< T >, pinhao::IfFormula< T >, and pinhao::FeatureFormula< T >.
virtual ValueType pinhao::FormulaBase::getType () const pure virtual
Gets the type of the Formula (what is the returning type).
Implemented in pinhao::BoolBinOpFormula< bool >, pinhao::BoolBinOpFormula< T >, pinhao::ArithBinOpFormula< T >, pinhao::LitFormula< T >, pinhao::IfFormula< T >, and pinhao::FeatureFormula< T >.
bool FormulaBase::isArithBinOp () const virtual
Returns true if it is a ArithBinOp formula.
Definition at line 216 of file Formula.cpp.
References pinhao::ArithBinOp, and getKind().
bool FormulaBase::isBoolBinOp () const virtual
Returns true if it is a BoolBinOp formula.
Definition at line 220 of file Formula.cpp.
References pinhao::BoolBinOp, and getKind().
bool FormulaBase::isFeature () const virtual
Returns true if it is a Feature formula.
Definition at line 224 of file Formula.cpp.
References pinhao::Feature, and getKind().
bool FormulaBase::isIf () const virtual
Returns true if it is a If formula.
Definition at line 228 of file Formula.cpp.
References getKind(), and pinhao::If.
bool FormulaBase::isLiteral () const virtual
Returns true if it is a Literal formula.
Definition at line 212 of file Formula.cpp.
References getKind(), and pinhao::Literal.
bool FormulaBase::operator!= (const FormulaBase & Rhs) const
Definition at line 236 of file Formula.cpp.
virtual bool pinhao::FormulaBase::operator< (const FormulaBase & Rhs) const pure virtual
Implemented in pinhao::BinOpFormulaBase< T, OpT >, pinhao::BinOpFormulaBase< bool, T >, pinhao::BinOpFormulaBase< T, T >, pinhao::BinOpFormulaBase< bool, bool >, pinhao::LitFormula< T >, pinhao::IfFormula< T >, and pinhao::FeatureFormula< T >.
bool FormulaBase::operator<= (const FormulaBase & Rhs) const
Definition at line 248 of file Formula.cpp.
virtual bool pinhao::FormulaBase::operator== (const FormulaBase & Rhs) const pure virtual
Implemented in pinhao::BinOpFormulaBase< T, OpT >, pinhao::BinOpFormulaBase< bool, T >, pinhao::BinOpFormulaBase< T, T >, pinhao::BinOpFormulaBase< bool, bool >, pinhao::LitFormula< T >, pinhao::IfFormula< T >, and pinhao::FeatureFormula< T >.
bool FormulaBase::operator> (const FormulaBase & Rhs) const
Definition at line 240 of file Formula.cpp.
bool FormulaBase::operator>= (const FormulaBase & Rhs) const
Definition at line 244 of file Formula.cpp.
void FormulaBase::print (std::ostream & Out = std::cout)
Prints to an std::ostream object the information of this Formula.
Definition at line 232 of file Formula.cpp.
References pinhao::YAMLWrapper::print().
virtual FormulaBase* pinhao::FormulaBase::simplify () pure virtual
Simplifies the current formula.
Implemented in pinhao::BinOpFormulaBase< T, OpT >, pinhao::BinOpFormulaBase< bool, T >, pinhao::BinOpFormulaBase< T, T >, pinhao::BinOpFormulaBase< bool, bool >, pinhao::LitFormula< T >, pinhao::IfFormula< T >, and pinhao::FeatureFormula< T >.
virtual void pinhao::FormulaBase::solveFor (FeatureSet * Set) pure virtual
Evaluates the Formula for the Set.
Implemented in pinhao::BinOpFormulaBase< T, OpT >, pinhao::BinOpFormulaBase< bool, T >, pinhao::BinOpFormulaBase< T, T >, pinhao::BinOpFormulaBase< bool, bool >, pinhao::LitFormula< T >, pinhao::IfFormula< T >, and pinhao::FeatureFormula< T >.