Pinhao: pinhao::FeatureSet Class Reference
pinhao::FeatureSet Class Reference
This class holds all enabled features.
#include <FeatureSet.h>
Classes
class iterator
Iterates over the features/sub-features of the enabled features.
Public Member Functions
~FeatureSet ()
uint64_t count ()
Returns the number of features (and subfeatures).
uint64_t count (FeatureKind, ValueType)
Returns the number of features with kind FKind, and type FType.
uint64_t count (FeatureKind)
Returns the number of features with kind FKind.
uint64_t count (ValueType)
Returns the number of features with type FType.
iterator get (uint64_t)
Gets an iterator to the Nth feature.
iterator get (uint64_t, FeatureKind, ValueType)
Gets an iterator to the Nth feature with kind FKind, and type FType.
iterator get (uint64_t, FeatureKind)
Gets an iterator to the Nth feature with kind FKind.
iterator get (uint64_t, ValueType)
Gets an iterator to the Nth feature with type FType.
template<class FeatureType >
FeatureType getFeature (std::string FeatureName, std::string SubfeatureName)
Gets a feature or sub-feature which has type FeatureType.
template<class FeatureType , class KeyType >
FeatureType getSubfeatureOfKey (std::string FeatureName, std::string SubfeatureName, KeyType Key)
Has the same functionality as the getFeature method, but it should be provided a key.
template<class FeatureType >
FeatureType getFeature (std::pair< std::string, std::string > FeaturePair)
template<class FeatureType , class KeyType >
FeatureType getSubfeatureOfKey (std::pair< std::string, std::string > FeaturePair, KeyType Key)
iterator begin (std::string FeatureName="")
Gets a iterator to the first feature.
iterator end (std::string FeatureName="")
Gets a iterator to the end of the features list.
Static Public Member Functions
static std::unique_ptr< FeatureSet > get ()
Constructs a FeatureSet object based on the EnableFeature.
static bool isEnabled (std::string FeatureName, std::string SubFeatureName="")
Returns true if the feature FeatureName is enabled. If SubFeatureName is provided, it returns true only if the sub-feature SubFeatureName is also enabled.
static bool isEnabled (std::pair< std::string, std::string > Pair)
static void enable (std::string FeatureName)
Enables the feature called FeatureName.
static void enable (std::string FeatureName, std::vector< std::string > SubFeatures)
Enables only the sub-features in the SubFeatures, of the feature called FeatureName.
static void disableAll ()
Disables all enabled features.
Private Member Functions
FeatureSet ()
Feature * getFeature (iterator)
Returns a pointer to a feature, based on the Iterator.
Private Attributes
std::map< std::string, std::unique_ptr< Feature > > Features
All the enabled features.
Static Private Attributes
static std::map< std::string, std::map< std::string, bool > > EnabledFeatures
Has the needed information to decide whether some feature must be enabled or not.
Friends
class FeatureSetWrapperPass
Detailed Description
This class holds all enabled features.
Definition at line 24 of file FeatureSet.h.
Constructor & Destructor Documentation
pinhao::FeatureSet::FeatureSet () inline private
Definition at line 33 of file FeatureSet.h.
References disableAll(), enable(), and isEnabled().
pinhao::FeatureSet::~FeatureSet () inline
Definition at line 113 of file FeatureSet.h.
References count().
Member Function Documentation
iterator pinhao::FeatureSet::begin (std::string FeatureName = "") inline
Gets a iterator to the first feature.
If the FeatureName is specified, it will return a iterator pointing to the first subfeature of the feature specified. If not, it will iterate over all sub-features enabled.
Parameters
FeatureName The name of the feature to be iterated over.
Definition at line 185 of file FeatureSet.h.
References pinhao::FeatureSet::iterator::FeatureName, and pinhao::FeatureSet::iterator::iterator().
uint64_t FeatureSet::count ()
Returns the number of features (and subfeatures).
Definition at line 96 of file FeatureSet.cpp.
uint64_t FeatureSet::count (FeatureKind FKind, ValueType FType)
Returns the number of features with kind FKind, and type FType.
Definition at line 86 of file FeatureSet.cpp.
References pinhao::Feature::getKind(), and pinhao::Feature::getType().
uint64_t FeatureSet::count (FeatureKind FKind)
Returns the number of features with kind FKind.
Definition at line 66 of file FeatureSet.cpp.
References pinhao::Feature::getKind().
uint64_t FeatureSet::count (ValueType FType)
Returns the number of features with type FType.
Definition at line 76 of file FeatureSet.cpp.
References pinhao::Feature::getType().
void FeatureSet::disableAll () static
Disables all enabled features.
Definition at line 53 of file FeatureSet.cpp.
References pinhao::Feature::getNumberOfSubFeatures(), and pinhao::Feature::isComposite().
void FeatureSet::enable (std::string FeatureName) static
Enables the feature called FeatureName.
Definition at line 39 of file FeatureSet.cpp.
void FeatureSet::enable (std::string FeatureName, std::vector< std::string > SubFeatures) static
Enables only the sub-features in the SubFeatures, of the feature called FeatureName.
Definition at line 46 of file FeatureSet.cpp.
iterator pinhao::FeatureSet::end (std::string FeatureName = "") inline
Gets a iterator to the end of the features list.
Definition at line 190 of file FeatureSet.h.
References pinhao::FeatureSet::iterator::FeatureName, and pinhao::FeatureSet::iterator::iterator().
std::unique_ptr< FeatureSet > FeatureSet::get () static
Constructs a FeatureSet object based on the EnableFeature.
Definition at line 20 of file FeatureSet.cpp.
References Features, and pinhao::FeatureRegistry::get().
FeatureSet::iterator FeatureSet::get (uint64_t N)
Gets an iterator to the Nth feature.
Definition at line 135 of file FeatureSet.cpp.
FeatureSet::iterator FeatureSet::get (uint64_t N, FeatureKind FKind, ValueType FType)
Gets an iterator to the Nth feature with kind FKind, and type FType.
Definition at line 124 of file FeatureSet.cpp.
References pinhao::Feature::getKind(), and pinhao::Feature::getType().
FeatureSet::iterator FeatureSet::get (uint64_t N, FeatureKind FKind)
Gets an iterator to the Nth feature with kind FKind.
Definition at line 104 of file FeatureSet.cpp.
References pinhao::Feature::getKind().
FeatureSet::iterator FeatureSet::get (uint64_t N, ValueType FType)
Gets an iterator to the Nth feature with type FType.
Definition at line 114 of file FeatureSet.cpp.
References pinhao::Feature::getType().
Feature * FeatureSet::getFeature (iterator It) private
Returns a pointer to a feature, based on the Iterator.
Definition at line 62 of file FeatureSet.cpp.
References pinhao::Feature::get().
template<class FeatureType > FeatureType pinhao::FeatureSet::getFeature (std::string FeatureName, std::string SubfeatureName) inline
Gets a feature or sub-feature which has type FeatureType.
If it should get a feature, then the variable SubfeatureName must be empty(""). Otherwise, when getting the sub-feature, it must be passed the parent FeatureName, since there may have sub-features with the same name.
Parameters
FeatureName The name of the feature or the parent feature.
SubfeatureName The name of the sub-feature if there is one.
Returns
The value of the feature/sub-feature desired.
Definition at line 146 of file FeatureSet.h.
References pinhao::FeatureSet::iterator::FeatureName, and pinhao::LinearFeature< ValueType >::getValueOf().
template<class FeatureType > FeatureType pinhao::FeatureSet::getFeature (std::pair< std::string, std::string > FeaturePair) inline
Definition at line 167 of file FeatureSet.h.
template<class FeatureType , class KeyType > FeatureType pinhao::FeatureSet::getSubfeatureOfKey (std::string FeatureName, std::string SubfeatureName, KeyType Key) inline
Has the same functionality as the getFeature method, but it should be provided a key.
Definition at line 157 of file FeatureSet.h.
References pinhao::FeatureSet::iterator::FeatureName, and pinhao::MappedFeature< KeyType, ValueType >::getValueOfKey().
template<class FeatureType , class KeyType > FeatureType pinhao::FeatureSet::getSubfeatureOfKey (std::pair< std::string, std::string > FeaturePair, KeyType Key) inline
Definition at line 172 of file FeatureSet.h.
bool FeatureSet::isEnabled (std::string FeatureName, std::string SubFeatureName = "") static
Returns true if the feature FeatureName is enabled. If SubFeatureName is provided, it returns true only if the sub-feature SubFeatureName is also enabled.
Definition at line 28 of file FeatureSet.cpp.
bool FeatureSet::isEnabled (std::pair< std::string, std::string > Pair) static
Definition at line 35 of file FeatureSet.cpp.
Friends And Related Function Documentation
friend class FeatureSetWrapperPass friend
Definition at line 192 of file FeatureSet.h.
Member Data Documentation
std::map< std::string, std::map< std::string, bool > > FeatureSet::EnabledFeatures static private
Has the needed information to decide whether some feature must be enabled or not.
Definition at line 28 of file FeatureSet.h.
std::map<std::string, std::unique_ptr<Feature> > pinhao::FeatureSet::Features private
All the enabled features.
Definition at line 31 of file FeatureSet.h.