Pinhao: pinhao::UniformRandom Class Reference
pinhao::UniformRandom Class Reference
Standard random number generator wrapper.
#include <Random.h>
Public Member Functions
UniformRandom ()
int getInt (int, int)
Returns a random generated int between two values.
double getReal ()
Returns a random generated double between 0.0 and 1.0.
Static Public Member Functions
static int getRandomInt (int, int)
Returns a random generated int with the singleton reference.
static double getRandomReal ()
Returns a random generated real between 0.0 and 1.0, with the singleton reference.
Static Private Member Functions
static UniformRandom & getUniformRandom ()
Gets a singleton reference to a UniformRandom object.
Private Attributes
std::default_random_engine Rng
std::uniform_real_distribution< double > Unif
Detailed Description
Standard random number generator wrapper.
Definition at line 17 of file Random.h.
Constructor & Destructor Documentation
UniformRandom::UniformRandom ()
Definition at line 14 of file Random.cpp.
References Rng.
Member Function Documentation
int UniformRandom::getInt (int From, int To)
Returns a random generated int between two values.
Definition at line 34 of file Random.cpp.
References getReal().
int UniformRandom::getRandomInt (int From, int To) static
Returns a random generated int with the singleton reference.
Definition at line 24 of file Random.cpp.
References getInt(), getUniformRandom(), and Unif.
double UniformRandom::getRandomReal () static
Returns a random generated real between 0.0 and 1.0, with the singleton reference.
Definition at line 29 of file Random.cpp.
References getReal(), getUniformRandom(), and Unif.
double UniformRandom::getReal ()
Returns a random generated double between 0.0 and 1.0.
Definition at line 40 of file Random.cpp.
References Rng, and Unif.
UniformRandom & UniformRandom::getUniformRandom () static private
Gets a singleton reference to a UniformRandom object.
Definition at line 19 of file Random.cpp.
References Unif.
Member Data Documentation
std::default_random_engine pinhao::UniformRandom::Rng private
Definition at line 19 of file Random.h.
std::uniform_real_distribution<double> pinhao::UniformRandom::Unif private
Definition at line 20 of file Random.h.