Pinhao: pinhao::VectorFeature< ElemType > Class Template Reference
pinhao::VectorFeature< ElemType > Class Template Reference
Implements a template vector feature class.
#include <VectorFeature.h>
Public Member Functions
virtual ~VectorFeature ()
VectorFeature (FeatureInfo *Info)
void setValueOf (std::string FeatureName, ElemType Elem) override
Sets the sub-feature with name FeatureName to Elem.
const ElemType & getValueOf (std::string FeatureName) const override
Gets the sub-feature, which has type ElemType, with name FeatureName.
virtual void append (YAML::Emitter &Emitter) const override
Appends to a YAML::Emitter this feature data.
virtual void get (const YAML::Node &Node) override
Gets the feature data from a YAML::Node.
Public Member Functions inherited from pinhao::LinearFeature< ElemType >
virtual ~LinearFeature ()
LinearFeature (FeatureInfo *Info)
Public Member Functions inherited from pinhao::Feature
virtual ~Feature ()
Feature (FeatureInfo *InfoPtr, FeatureKind FKind)
Constructs a Feature with the information FeatInfo.
std::string getName () const
Gets the name of the feature.
std::string getDescription () const
Gets the description of the feature.
ValueType getType () const
Gets the ValueType of the feature.
uint64_t getNumberOfSubFeatures () const
Gets the description of the sub-feature with name SubFeatureName.
bool hasSubFeature (std::string SubFeatureName) const
Returns true if there is a sub-feature with name SubFeatureName.
std::string getSubFeatureDescription (std::string SubFeatureName) const
Gets the description of the sub-feature with name SubFeatureName.
FeatureKind getKind () const
Returns the FeatureKind.
bool isComposite () const
Returns true if the feature has more than two sub-features.
bool isProcessed () const
Returns true if the feature has already been processed.
bool isLinear () const
Returns true if it is a LinearFeature.
bool isMapped () const
Returns true if it is a MappedFeature.
bool isStaticFeature () const
Returns true if it is a static feature.
bool isDynamicFeature () const
Returns true if it is a dynamic feature.
iterator begin () const
Gets the begin iterator of the Info.
iterator end () const
Gets the end iterator of the Info.
void print (std::ostream &Out=std::cout)
Prints its information into a std::ostream object in the format yaml.
virtual void processModule (llvm::Module &Module)=0
Gets the necessary information from a llvm::Module.
virtual std::unique_ptr< Feature > clone () const =0
Clones the feature.
Protected Attributes
std::vector< ElemType > TheFeature
The vector container of the feature itself.
Protected Attributes inherited from pinhao::Feature
std::shared_ptr< FeatureInfo > Info
bool Processed
Additional Inherited Members
Public Types inherited from pinhao::Feature
typedef std::map< std::string, std::string >::iterator iterator
Detailed Description
template<class ElemType>
class pinhao::VectorFeature< ElemType >
Implements a template vector feature class.
All the vector-like features must implement this class, giving its type as the template.
Definition at line 25 of file VectorFeature.h.
Constructor & Destructor Documentation
template<class ElemType> virtual pinhao::VectorFeature< ElemType >::~VectorFeature () inline virtual
Definition at line 31 of file VectorFeature.h.
References pinhao::VectorFeature< ElemType >::append(), pinhao::VectorFeature< ElemType >::getValueOf(), pinhao::Feature::Info, pinhao::VectorFeature< ElemType >::setValueOf(), and pinhao::VectorFeature< ElemType >::VectorFeature().
template<class ElemType > VectorFeature::VectorFeature (FeatureInfo * Info)
Definition at line 62 of file VectorFeature.h.
References pinhao::CompositeFeatureInfo::getNumberOfSubFeatures(), pinhao::Feature::isComposite(), and pinhao::VectorFeature< ElemType >::TheFeature.
Member Function Documentation
template<class ElemType > void VectorFeature::append (YAML::Emitter & Emitter) const override virtual
Appends to a YAML::Emitter this feature data.
Parameters
Emitter The place where the data information will be appended.
Implements pinhao::Feature.
Definition at line 85 of file VectorFeature.h.
References pinhao::YAMLWrapper::append().
template<class ElemType > void VectorFeature::get (const YAML::Node & Node) override virtual
Gets the feature data from a YAML::Node.
Implements pinhao::Feature.
Definition at line 90 of file VectorFeature.h.
References pinhao::YAMLWrapper::fill().
template<class ElemType > const ElemType & VectorFeature::getValueOf (std::string FeatureName) const override virtual
Gets the sub-feature, which has type ElemType, with name FeatureName.
Parameters
FeatureName The name of the desired sub-feature.
Returns
A pointer to the sub-feature value with const modifier.
Implements pinhao::LinearFeature< ElemType >.
Definition at line 77 of file VectorFeature.h.
References pinhao::CompositeFeatureInfo::getIndexOfSubFeature(), pinhao::Feature::hasSubFeature(), pinhao::Feature::Info, and pinhao::VectorFeature< ElemType >::TheFeature.
template<class ElemType > void VectorFeature::setValueOf (std::string FeatureName, ElemType Elem) override virtual
Sets the sub-feature with name FeatureName to Elem.
Parameters
FeatureName The name of the desired sub-feature.
Elem The element that will replace the old element.
Implements pinhao::LinearFeature< ElemType >.
Definition at line 69 of file VectorFeature.h.
References pinhao::CompositeFeatureInfo::getIndexOfSubFeature(), pinhao::Feature::hasSubFeature(), pinhao::Feature::Info, and pinhao::VectorFeature< ElemType >::TheFeature.
Member Data Documentation
template<class ElemType> std::vector<ElemType> pinhao::VectorFeature< ElemType >::TheFeature protected
The vector container of the feature itself.
Definition at line 28 of file VectorFeature.h.