Pinhao: pinhao::FeatureFormula< T > Class Template Reference
pinhao::FeatureFormula< T > Class Template Reference
Holds a pair of std::strings. The first represents the feature, and the second represents the sub-feature (if there is one).
#include <FeatureFormula.h>
Public Member Functions
ValueType getType () const override
Gets the type of the Formula (what is the returning type).
FormulaKind getKind () const override
Gets a FormulaKind of this object.
void evolve (Evolution *) override
Evolves this formula, based on the Evolution algorithm.
FormulaBase * simplify () override
Simplifies the current formula.
void generate (FeatureSet *Set) override
Randomizes the generations of a Formula.
void solveFor (FeatureSet *Set) override
Evaluates the Formula for the Set.
bool operator== (const FormulaBase &Rhs) const override
bool operator< (const FormulaBase &Rhs) const override
std::unique_ptr< FormulaBase > clone () override
Clones (deep copy) the formula.
Public Member Functions inherited from pinhao::Formula< T >
virtual ~Formula ()
T & getValue ()
Gets a reference to the value.
T getValue () const
Gets a copy of the value.
virtual ValueType getOperandsType () const
Return the type of the operands. If it has none, it returns the type of the Formula.
Public Member Functions inherited from pinhao::FormulaBase
virtual ~FormulaBase ()
virtual bool isLiteral () const
Returns true if it is a Literal formula.
virtual bool isArithBinOp () const
Returns true if it is a ArithBinOp formula.
virtual bool isBoolBinOp () const
Returns true if it is a BoolBinOp formula.
virtual bool isFeature () const
Returns true if it is a Feature formula.
virtual bool isIf () const
Returns true if it is a If formula.
bool operator!= (const FormulaBase &Rhs) const
bool operator> (const FormulaBase &Rhs) const
bool operator>= (const FormulaBase &Rhs) const
bool operator<= (const FormulaBase &Rhs) const
void print (std::ostream &Out=std::cout)
Prints to an std::ostream object the information of this Formula.
Public Attributes
std::pair< std::string, std::string > FeaturePair
Additional Inherited Members
Static Protected Member Functions inherited from pinhao::Formula< T >
static T getFormulaValue (const FormulaBase *Base)
A wrapper that gets the value yielded.
Protected Attributes inherited from pinhao::Formula< T >
T Value
The value that is yielded after evaluation.
Detailed Description
template<class T>
class pinhao::FeatureFormula< T >
Holds a pair of std::strings. The first represents the feature, and the second represents the sub-feature (if there is one).
Definition at line 19 of file FeatureFormula.h.
Member Function Documentation
template<class T > std::unique_ptr< pinhao::FormulaBase > pinhao::FeatureFormula< T >::clone () override virtual
Clones (deep copy) the formula.
Implements pinhao::FormulaBase.
Definition at line 91 of file FeatureFormula.h.
References pinhao::FeatureFormula< T >::FeaturePair.
template<class T > void pinhao::FeatureFormula< T >::evolve (Evolution *) override virtual
Evolves this formula, based on the Evolution algorithm.
Implements pinhao::FormulaBase.
Definition at line 41 of file FeatureFormula.h.
References pinhao::Evolution::evolve(), and pinhao::FeatureFormula< T >::FeaturePair.
template<class T > void pinhao::FeatureFormula< T >::generate (FeatureSet * Set) override virtual
Randomizes the generations of a Formula.
Implements pinhao::FormulaBase.
Definition at line 61 of file FeatureFormula.h.
References pinhao::FeatureSet::count(), pinhao::FeatureFormula< T >::FeaturePair, pinhao::FeatureSet::get(), and pinhao::UniformRandom::getRandomInt().
template<class T > pinhao::FormulaKind pinhao::FeatureFormula< T >::getKind () const override virtual
Gets a FormulaKind of this object.
Implements pinhao::FormulaBase.
Definition at line 56 of file FeatureFormula.h.
References pinhao::Feature.
template<class T > pinhao::ValueType pinhao::FeatureFormula< T >::getType () const override virtual
Gets the type of the Formula (what is the returning type).
Implements pinhao::FormulaBase.
Definition at line 51 of file FeatureFormula.h.
template<class T > bool pinhao::FeatureFormula< T >::operator< (const FormulaBase & Rhs) const override virtual
Implements pinhao::FormulaBase.
Definition at line 81 of file FeatureFormula.h.
References pinhao::FeatureFormula< T >::FeaturePair, pinhao::FeatureFormula< T >::getKind(), pinhao::FormulaBase::getKind(), pinhao::FeatureFormula< T >::getType(), and pinhao::FormulaBase::getType().
template<class T > bool pinhao::FeatureFormula< T >::operator== (const FormulaBase & Rhs) const override virtual
Implements pinhao::FormulaBase.
Definition at line 73 of file FeatureFormula.h.
References pinhao::FeatureFormula< T >::FeaturePair, pinhao::FeatureFormula< T >::getKind(), pinhao::FormulaBase::getKind(), pinhao::FeatureFormula< T >::getType(), and pinhao::FormulaBase::getType().
template<class T > pinhao::FormulaBase * pinhao::FeatureFormula< T >::simplify () override virtual
Simplifies the current formula.
Implements pinhao::FormulaBase.
Definition at line 46 of file FeatureFormula.h.
template<class T > void pinhao::FeatureFormula< T >::solveFor (FeatureSet * Set) override virtual
Evaluates the Formula for the Set.
Implements pinhao::FormulaBase.
Definition at line 68 of file FeatureFormula.h.
References pinhao::FeatureFormula< T >::FeaturePair, pinhao::FeatureSet::getFeature(), and pinhao::Formula< T >::Value.
Member Data Documentation
template<class T> std::pair<std::string, std::string> pinhao::FeatureFormula< T >::FeaturePair
Definition at line 21 of file FeatureFormula.h.