Pinhao: pinhao::FeatureSet::iterator Class Reference
pinhao::FeatureSet::iterator Class Reference
Iterates over the features/sub-features of the enabled features.
#include <FeatureSet.h>
Public Member Functions
iterator ()
iterator (EnabledFeaturesMap *M, EnabledFeaturesMap::iterator It, std::string Name="")
const PairType * operator-> () const
PairType & operator* ()
iterator & operator++ ()
iterator operator++ (int)
bool operator== (const iterator &It)
bool operator!= (const iterator &It)
Private Types
typedef std::map< std::string, std::unique_ptr< Feature > > EnabledFeaturesMap
typedef value_type PairType
Private Member Functions
void incMapIterator ()
void setPair ()
void update ()
Private Attributes
PairType Pair
The actual pair that will be returned.
Feature::iterator FeatureIterator
The iterator of composite features.
EnabledFeaturesMap * Map
A pointer to the map to be iterated.
EnabledFeaturesMap::iterator MapIterator
The current iterator position in the map.
std::string FeatureName
The name of the feature being iterated, if specified.
Detailed Description
Iterates over the features/sub-features of the enabled features.
It will iterate over the features enabled. More specifically, over a FeatureSet. For each Feature or SubFeature found, it will return a iterator pointing to a std::pair.
{ "FeatureName", "SubFeatureName" }
If there is no sub-feature in the feature, an empty string is returned.
Definition at line 66 of file FeatureSet.h.
Member Typedef Documentation
typedef std::map<std::string, std::unique_ptr<Feature> > pinhao::FeatureSet::iterator::EnabledFeaturesMap private
Definition at line 68 of file FeatureSet.h.
typedef value_type pinhao::FeatureSet::iterator::PairType private
Definition at line 69 of file FeatureSet.h.
Constructor & Destructor Documentation
pinhao::FeatureSet::iterator::iterator () inline
Definition at line 91 of file FeatureSet.h.
References pinhao::FeatureSet::getFeature(), operator!=(), operator*(), operator++(), operator->(), and operator==().
FeatureSet::iterator::iterator (EnabledFeaturesMap * M, EnabledFeaturesMap::iterator It, std::string Name = "")
Parameters
M Pointer to the map that it should iterate.
It The initial iterator position.
Name A feature name that it should iterate.
Definition at line 146 of file FeatureSet.cpp.
References FeatureIterator, FeatureName, Map, MapIterator, and update().
Member Function Documentation
void FeatureSet::iterator::incMapIterator () private
Definition at line 180 of file FeatureSet.cpp.
References FeatureIterator, Map, and MapIterator.
bool FeatureSet::iterator::operator!= (const iterator & It)
Definition at line 222 of file FeatureSet.cpp.
References pinhao::FeatureSetWrapperPass::ID.
FeatureSet::iterator::PairType & FeatureSet::iterator::operator* ()
Definition at line 176 of file FeatureSet.cpp.
References Pair.
FeatureSet::iterator & FeatureSet::iterator::operator++ ()
Definition at line 186 of file FeatureSet.cpp.
References FeatureIterator, FeatureName, incMapIterator(), Map, MapIterator, and update().
FeatureSet::iterator FeatureSet::iterator::operator++ (int)
Definition at line 207 of file FeatureSet.cpp.
References operator++().
const FeatureSet::iterator::PairType * FeatureSet::iterator::operator-> () const
Definition at line 172 of file FeatureSet.cpp.
References Pair.
bool FeatureSet::iterator::operator== (const iterator & It)
Definition at line 213 of file FeatureSet.cpp.
References FeatureIterator, Map, and MapIterator.
void FeatureSet::iterator::setPair () private
Definition at line 157 of file FeatureSet.cpp.
References FeatureIterator, Map, MapIterator, and Pair.
void FeatureSet::iterator::update () private
Definition at line 166 of file FeatureSet.cpp.
References pinhao::FeatureSet::isEnabled(), Map, MapIterator, Pair, and setPair().
Member Data Documentation
Feature::iterator pinhao::FeatureSet::iterator::FeatureIterator private
The iterator of composite features.
Definition at line 75 of file FeatureSet.h.
std::string pinhao::FeatureSet::iterator::FeatureName private
The name of the feature being iterated, if specified.
Definition at line 84 of file FeatureSet.h.
EnabledFeaturesMap* pinhao::FeatureSet::iterator::Map private
A pointer to the map to be iterated.
Definition at line 78 of file FeatureSet.h.
EnabledFeaturesMap::iterator pinhao::FeatureSet::iterator::MapIterator private
The current iterator position in the map.
Definition at line 81 of file FeatureSet.h.
PairType pinhao::FeatureSet::iterator::Pair private
The actual pair that will be returned.
Definition at line 72 of file FeatureSet.h.