Pinhao: pinhao::GEOSWrapper Class Reference
pinhao::GEOSWrapper Class Reference
This class is actually a wrapper to a set of functions of the GEOS framework.
#include <GEOSWrapper.h>
Static Public Member Functions
static void loadCallCostFile (llvm::Module &)
Loads the callcost provided.
static void getFrequencies (std::shared_ptr< ProfileModule >)
Runs the llvm::Module inside the ProfileModule, in order to get the BasicBlock frequencies.
static std::vector< double > repairAndAnalyse (llvm::Module &)
Repairs the frequencies (from the instructions), and calculates all GEOS' costs.
static std::vector< double > getFrequenciesAndAnalyse (llvm::Module &)
Gets the frequencies by running the llvm::Module, and calculates all GEOS' costs.
Static Private Member Functions
static std::vector< double > getAnalysisCost (std::shared_ptr< ProfileModule >)
Gets all GEOS' measurements of a ProfileModule.
static void propagateToInstructions (ProfileModule &)
Propagates the frequencies stored in the ProfileModule to the instructions.
Detailed Description
This class is actually a wrapper to a set of functions of the GEOS framework.
The functions that calculates the costs returns a std::vector<double> with all GEOS' costs. They are:
RegisterUse
InstructionCache
StaticInstruction
TTIInstruction
Branch
Call
NonArchSensitive
ArchSensitive
Definition at line 36 of file GEOSWrapper.h.
Member Function Documentation
std::vector< double > GEOSWrapper::getAnalysisCost (std::shared_ptr< ProfileModule > PModule) static private
Gets all GEOS' measurements of a ProfileModule.
Definition at line 27 of file GEOSWrapper.cpp.
void GEOSWrapper::getFrequencies (std::shared_ptr< ProfileModule > PModule) static
Runs the llvm::Module inside the ProfileModule, in order to get the BasicBlock frequencies.
Definition at line 78 of file GEOSWrapper.cpp.
References propagateToInstructions().
std::vector< double > GEOSWrapper::getFrequenciesAndAnalyse (llvm::Module & M) static
Gets the frequencies by running the llvm::Module, and calculates all GEOS' costs.
Definition at line 94 of file GEOSWrapper.cpp.
References getAnalysisCost(), and getFrequencies().
void GEOSWrapper::loadCallCostFile (llvm::Module & M) static
Loads the callcost provided.
Definition at line 73 of file GEOSWrapper.cpp.
void GEOSWrapper::propagateToInstructions (ProfileModule & PModule) static private
Propagates the frequencies stored in the ProfileModule to the instructions.
Definition at line 60 of file GEOSWrapper.cpp.
std::vector< double > GEOSWrapper::repairAndAnalyse (llvm::Module & M) static
Repairs the frequencies (from the instructions), and calculates all GEOS' costs.
Definition at line 88 of file GEOSWrapper.cpp.
References getAnalysisCost().