Pinhao: pinhao::OptimizationSet Class Reference
pinhao::OptimizationSet Class Reference
Holds all enabled optimizations as well as the number of repetition of each one.
#include <OptimizationSet.h>
Public Types
typedef std::map< OptimizationInfo, uint64_t >::iterator SetIterator
Public Member Functions
OptimizationSet ()
~OptimizationSet ()
bool hasEnabled (Optimization Opt)
Returns true if the Optimization Opt has already been enabled.
bool hasEnabled (OptimizationInfo Info)
Returns true if the Optimization Opt with the same information has already been enabled.
void disableOptimization (Optimization Opt)
Removes Opt, if enabled.
void disableOptimization (OptimizationInfo Info)
Removes Opt with information Info, if enabled.
void enableOptimization (Optimization Opt, uint64_t Repetition=1)
Enables the Opt with default properties.
void enableOptimization (OptimizationInfo Info, uint64_t Repetition=1)
Enables a optimization with specific OptimizationInfo.
void enableOptimizations (std::vector< Optimization > Opts)
Enables the optimizations with default properties.
void enableAllOptimizations ()
Enables all optimizations with default properties.
void enableModuleOptimizations ()
Enables all module optimizations with default properties.
void enableFunctionOptimizations ()
Enables all function optimizations with default properties.
void addOptimization (Optimization Opt)
Enables if doesn't exist, add one to the repetition if exists.
void addOptimization (OptimizationInfo Info)
Enables if doesn't exist, add one to the repetition if exists.
void setRepetition (Optimization Opt, uint64_t Rep)
Sets the repetition number to Rep, if the optimization is enabled.
void setRepetition (OptimizationInfo Info, uint64_t Rep)
Sets the repetition number to Rep, if the optimization with information Info is enabled.
uint64_t getRepetition (Optimization Opt)
Gets the repetition number to Rep, if the optimization is enabled.
uint64_t getRepetition (OptimizationInfo Info)
Gets the repetition number to Rep, if the optimization with information Info is enabled.
void generateRandomSequenceIfNone ()
Generates a random sequence (it will be the default sequence), in order to compile.
uint64_t size ()
Returns the number of enabled optimizations.
SetIterator begin ()
SetIterator end ()
Static Public Member Functions
static std::unique_ptr< OptimizationSet > generate (OptimizationSequence Seq)
Constructs an OptimizationSet from a given OptimizationSequence.
Public Attributes
OptimizationSequence * DefaultSequence
The default sequence in which it will be compiled.
Private Attributes
std::map< OptimizationInfo, uint64_t > EnabledOptimizations
The enabled optimizations paired with its repetition number.
Detailed Description
Holds all enabled optimizations as well as the number of repetition of each one.
Definition at line 65 of file OptimizationSet.h.
Member Typedef Documentation
typedef std::map<OptimizationInfo, uint64_t>::iterator pinhao::OptimizationSet::SetIterator
Definition at line 138 of file OptimizationSet.h.
Constructor & Destructor Documentation
OptimizationSet::OptimizationSet ()
Definition at line 14 of file OptimizationSet.cpp.
References DefaultSequence.
OptimizationSet::~OptimizationSet ()
Definition at line 18 of file OptimizationSet.cpp.
Member Function Documentation
void OptimizationSet::addOptimization (Optimization Opt)
Enables if doesn't exist, add one to the repetition if exists.
If the optimization with default information is already enabled, the number of repetition is increased by one. Otherwise, it enables the optimization.
Definition at line 73 of file OptimizationSet.cpp.
void OptimizationSet::addOptimization (OptimizationInfo Info)
Enables if doesn't exist, add one to the repetition if exists.
If there is already an optimization with the same information as Info, the number of repetition is increased by one. Otherwise, it enables the optimization.
Definition at line 78 of file OptimizationSet.cpp.
References enableOptimization(), getRepetition(), hasEnabled(), and setRepetition().
SetIterator pinhao::OptimizationSet::begin () inline
Definition at line 139 of file OptimizationSet.h.
void OptimizationSet::disableOptimization (Optimization Opt)
Removes Opt, if enabled.
Definition at line 31 of file OptimizationSet.cpp.
void OptimizationSet::disableOptimization (OptimizationInfo Info)
Removes Opt with information Info, if enabled.
Definition at line 36 of file OptimizationSet.cpp.
References EnabledOptimizations, and hasEnabled().
void OptimizationSet::enableAllOptimizations ()
Enables all optimizations with default properties.
Definition at line 56 of file OptimizationSet.cpp.
References enableOptimization(), and pinhao::getOptimization().
void OptimizationSet::enableFunctionOptimizations ()
Enables all function optimizations with default properties.
Definition at line 67 of file OptimizationSet.cpp.
References enableOptimization(), pinhao::getOptimization(), and pinhao::getPassKind().
void OptimizationSet::enableModuleOptimizations ()
Enables all module optimizations with default properties.
Definition at line 61 of file OptimizationSet.cpp.
References enableOptimization(), pinhao::getOptimization(), and pinhao::getPassKind().
void OptimizationSet::enableOptimization (Optimization Opt, uint64_t Repetition = 1)
Enables the Opt with default properties.
Definition at line 41 of file OptimizationSet.cpp.
void OptimizationSet::enableOptimization (OptimizationInfo Info, uint64_t Repetition = 1)
Enables a optimization with specific OptimizationInfo.
Definition at line 46 of file OptimizationSet.cpp.
References EnabledOptimizations, and hasEnabled().
void OptimizationSet::enableOptimizations (std::vector< Optimization > Opts)
Enables the optimizations with default properties.
Definition at line 51 of file OptimizationSet.cpp.
References enableOptimization().
SetIterator pinhao::OptimizationSet::end () inline
Definition at line 140 of file OptimizationSet.h.
std::unique_ptr< OptimizationSet > OptimizationSet::generate (OptimizationSequence Seq) static
Constructs an OptimizationSet from a given OptimizationSequence.
Definition at line 112 of file OptimizationSet.cpp.
References addOptimization(), and OptimizationSet().
void OptimizationSet::generateRandomSequenceIfNone ()
Generates a random sequence (it will be the default sequence), in order to compile.
Definition at line 103 of file OptimizationSet.cpp.
References DefaultSequence, and pinhao::OptimizationSequence::generate().
uint64_t OptimizationSet::getRepetition (Optimization Opt)
Gets the repetition number to Rep, if the optimization is enabled.
Definition at line 93 of file OptimizationSet.cpp.
uint64_t OptimizationSet::getRepetition (OptimizationInfo Info)
Gets the repetition number to Rep, if the optimization with information Info is enabled.
Definition at line 98 of file OptimizationSet.cpp.
References EnabledOptimizations, and hasEnabled().
bool OptimizationSet::hasEnabled (Optimization Opt)
Returns true if the Optimization Opt has already been enabled.
Definition at line 22 of file OptimizationSet.cpp.
bool OptimizationSet::hasEnabled (OptimizationInfo Info)
Returns true if the Optimization Opt with the same information has already been enabled.
Definition at line 27 of file OptimizationSet.cpp.
References EnabledOptimizations.
void OptimizationSet::setRepetition (Optimization Opt, uint64_t Rep)
Sets the repetition number to Rep, if the optimization is enabled.
Definition at line 83 of file OptimizationSet.cpp.
void OptimizationSet::setRepetition (OptimizationInfo Info, uint64_t Rep)
Sets the repetition number to Rep, if the optimization with information Info is enabled.
Definition at line 88 of file OptimizationSet.cpp.
References EnabledOptimizations, and hasEnabled().
uint64_t OptimizationSet::size ()
Returns the number of enabled optimizations.
Definition at line 108 of file OptimizationSet.cpp.
References EnabledOptimizations.
Member Data Documentation
OptimizationSequence* pinhao::OptimizationSet::DefaultSequence
The default sequence in which it will be compiled.
Definition at line 75 of file OptimizationSet.h.
std::map<OptimizationInfo, uint64_t> pinhao::OptimizationSet::EnabledOptimizations private
The enabled optimizations paired with its repetition number.
Definition at line 68 of file OptimizationSet.h.