Pinhao: pinhao::StdMapKeyIterator< KType, VType > Class Template Reference
pinhao::StdMapKeyIterator< KType, VType > Class Template Reference
Concrete class that iterates over the keys of the stl provided std::map class.
#include <Iterator.h>
Public Member Functions
StdMapKeyIterator ()
StdMapKeyIterator (Map *M, typename Map::iterator It)
const KType * operator-> () const override
const KType & operator* () override
KeyIterator< KType > & operator++ () override
It will return a reference, as it can't be instantiated.
bool operator== (const KeyIterator< KType > &It) override
bool operator!= (const KeyIterator< KType > &It) override
Public Member Functions inherited from pinhao::KeyIterator< KType >
virtual ~KeyIterator ()
Private Types
typedef std::map< KType, VType > Map
Private Member Functions
void updateCurrentPtr ()
Private Attributes
Map * ThisMap
Map::iterator CurrentIt
const KType * CurrentPtr
Detailed Description
template<class KType, class VType>
class pinhao::StdMapKeyIterator< KType, VType >
Concrete class that iterates over the keys of the stl provided std::map class.
Definition at line 41 of file Iterator.h.
Member Typedef Documentation
template<class KType, class VType> typedef std::map<KType, VType> pinhao::StdMapKeyIterator< KType, VType >::Map private
Definition at line 43 of file Iterator.h.
Constructor & Destructor Documentation
template<class KType, class VType> pinhao::StdMapKeyIterator< KType, VType >::StdMapKeyIterator () inline
Definition at line 52 of file Iterator.h.
References pinhao::KeyIterator< KType >::operator!=(), pinhao::KeyIterator< KType >::operator*(), pinhao::KeyIterator< KType >::operator++(), pinhao::KeyIterator< KType >::operator->(), and pinhao::KeyIterator< KType >::operator==().
template<class KType , class VType > pinhao::StdMapKeyIterator< KType, VType >::StdMapKeyIterator (Map * M, typename Map::iterator It)
Definition at line 65 of file Iterator.h.
References pinhao::StdMapKeyIterator< KType, VType >::updateCurrentPtr().
Member Function Documentation
template<class KType , class VType > bool pinhao::StdMapKeyIterator< KType, VType >::operator!= (const KeyIterator< KType > & It) override virtual
Implements pinhao::KeyIterator< KType >.
Definition at line 103 of file Iterator.h.
template<class KType , class VType > const KType & pinhao::StdMapKeyIterator< KType, VType >::operator* () override virtual
Implements pinhao::KeyIterator< KType >.
Definition at line 84 of file Iterator.h.
References pinhao::StdMapKeyIterator< KType, VType >::CurrentPtr.
template<class KType , class VType > pinhao::KeyIterator< KType > & pinhao::StdMapKeyIterator< KType, VType >::operator++ () override virtual
It will return a reference, as it can't be instantiated.
Implements pinhao::KeyIterator< KType >.
Definition at line 89 of file Iterator.h.
References pinhao::StdMapKeyIterator< KType, VType >::CurrentIt, and pinhao::StdMapKeyIterator< KType, VType >::updateCurrentPtr().
template<class KType , class VType > const KType * pinhao::StdMapKeyIterator< KType, VType >::operator-> () const override virtual
Implements pinhao::KeyIterator< KType >.
Definition at line 79 of file Iterator.h.
References pinhao::StdMapKeyIterator< KType, VType >::CurrentPtr.
template<class KType , class VType > bool pinhao::StdMapKeyIterator< KType, VType >::operator== (const KeyIterator< KType > & It) override virtual
Implements pinhao::KeyIterator< KType >.
Definition at line 96 of file Iterator.h.
References pinhao::StdMapKeyIterator< KType, VType >::CurrentPtr, and pinhao::StdMapKeyIterator< KType, VType >::ThisMap.
template<class KType , class VType > void pinhao::StdMapKeyIterator< KType, VType >::updateCurrentPtr () private
Definition at line 71 of file Iterator.h.
References pinhao::StdMapKeyIterator< KType, VType >::CurrentIt, pinhao::StdMapKeyIterator< KType, VType >::CurrentPtr, and pinhao::StdMapKeyIterator< KType, VType >::ThisMap.
Member Data Documentation
template<class KType, class VType> Map::iterator pinhao::StdMapKeyIterator< KType, VType >::CurrentIt private
Definition at line 46 of file Iterator.h.
template<class KType, class VType> const KType* pinhao::StdMapKeyIterator< KType, VType >::CurrentPtr private
Definition at line 47 of file Iterator.h.
template<class KType, class VType> Map* pinhao::StdMapKeyIterator< KType, VType >::ThisMap private
Definition at line 45 of file Iterator.h.