Pinhao: pinhao::StringFeature Class Reference
pinhao::StringFeature Class Reference
Implements a string version of a linear feature.
#include <Features.h>
Public Member Functions
virtual ~StringFeature ()
StringFeature (FeatureInfo *Info)
void setValueOf (std::string FeatureName, std::string Value) override
Sets the string feature to New.
const std::string & getValueOf (std::string FeatureName) const override
Gets the string feature (the FeatureName must be the same as this feature's name).
void append (YAML::Emitter &Emitter) const override
Appends to a YAML::Emitter this feature data.
void get (const YAML::Node &Node) override
Gets the feature data from a YAML::Node.
Public Member Functions inherited from pinhao::LinearFeature< std::string >
virtual ~LinearFeature ()
LinearFeature (FeatureInfo *Info)
Public Member Functions inherited from pinhao::Feature
virtual ~Feature ()
Feature (FeatureInfo *InfoPtr, FeatureKind FKind)
Constructs a Feature with the information FeatInfo.
std::string getName () const
Gets the name of the feature.
std::string getDescription () const
Gets the description of the feature.
ValueType getType () const
Gets the ValueType of the feature.
uint64_t getNumberOfSubFeatures () const
Gets the description of the sub-feature with name SubFeatureName.
bool hasSubFeature (std::string SubFeatureName) const
Returns true if there is a sub-feature with name SubFeatureName.
std::string getSubFeatureDescription (std::string SubFeatureName) const
Gets the description of the sub-feature with name SubFeatureName.
FeatureKind getKind () const
Returns the FeatureKind.
bool isComposite () const
Returns true if the feature has more than two sub-features.
bool isProcessed () const
Returns true if the feature has already been processed.
bool isLinear () const
Returns true if it is a LinearFeature.
bool isMapped () const
Returns true if it is a MappedFeature.
bool isStaticFeature () const
Returns true if it is a static feature.
bool isDynamicFeature () const
Returns true if it is a dynamic feature.
iterator begin () const
Gets the begin iterator of the Info.
iterator end () const
Gets the end iterator of the Info.
void print (std::ostream &Out=std::cout)
Prints its information into a std::ostream object in the format yaml.
virtual void processModule (llvm::Module &Module)=0
Gets the necessary information from a llvm::Module.
virtual std::unique_ptr< Feature > clone () const =0
Clones the feature.
Protected Attributes
std::string TheFeature
The string feature "container".
Protected Attributes inherited from pinhao::Feature
std::shared_ptr< FeatureInfo > Info
bool Processed
Additional Inherited Members
Public Types inherited from pinhao::Feature
typedef std::map< std::string, std::string >::iterator iterator
Detailed Description
Implements a string version of a linear feature.
As it is just a string, it can have this implementation. Classes that extend this one can override the implementation.
Definition at line 79 of file Features.h.
Constructor & Destructor Documentation
virtual pinhao::StringFeature::~StringFeature () inline virtual
Definition at line 85 of file Features.h.
References pinhao::Feature::append(), pinhao::LinearFeature< ValueType >::getValueOf(), pinhao::Feature::Info, and pinhao::LinearFeature< ValueType >::setValueOf().
StringFeature::StringFeature (FeatureInfo * Info)
Definition at line 19 of file Features.cpp.
Member Function Documentation
void StringFeature::append (YAML::Emitter & Emitter) const override virtual
Appends to a YAML::Emitter this feature data.
Parameters
Emitter The place where the data information will be appended.
Implements pinhao::Feature.
Definition at line 33 of file Features.cpp.
References pinhao::YAMLWrapper::append().
void StringFeature::get (const YAML::Node & Node) override virtual
Gets the feature data from a YAML::Node.
Implements pinhao::Feature.
Definition at line 37 of file Features.cpp.
References pinhao::YAMLWrapper::fill().
const std::string & StringFeature::getValueOf (std::string FeatureName) const override virtual
Gets the string feature (the FeatureName must be the same as this feature's name).
Implements pinhao::LinearFeature< std::string >.
Definition at line 28 of file Features.cpp.
References pinhao::Feature::Info, and TheFeature.
void StringFeature::setValueOf (std::string FeatureName, std::string Value) override virtual
Sets the string feature to New.
Implements pinhao::LinearFeature< std::string >.
Definition at line 23 of file Features.cpp.
References pinhao::Feature::Info, and TheFeature.
Member Data Documentation
std::string pinhao::StringFeature::TheFeature protected
The string feature "container".
Definition at line 82 of file Features.h.