Pinhao: pinhao::YAMLWrapper Class Reference
pinhao::YAMLWrapper Class Reference
This class is a wrapper class for the yaml-cpp library.
#include <YAMLWrapper.h>
Public Types
typedef const YAML::Node ConstNode
typedef YAML::Emitter Emitter
Public Member Functions
template<>
void append (const Candidate &, Emitter &)
template<>
void fill (Candidate &, ConstNode &)
template<class Type >
void fill (VectorFeature< Type > &Vf, ConstNode &Node)
template<class Type >
void append (const VectorFeature< Type > &Vf, Emitter &E)
template<class KType , class VType >
void fill (MapFeature< KType, VType > &Mf, ConstNode &Node)
template<class KType , class VType >
void append (const MapFeature< KType, VType > &Mf, Emitter &E)
template<class KType , class VType >
void fill (MapVectorFeature< KType, VType > &Mvf, ConstNode &Node)
template<class KType , class VType >
void append (const MapVectorFeature< KType, VType > &Mvf, Emitter &E)
template<>
std::unique_ptr< FormulaBase > get (ConstNode &)
template<>
void append (const FormulaBase &, Emitter &)
template<>
void fill (void *&, ConstNode &)
template<>
void append (void *const &, Emitter &)
template<>
void fill (StringFeature &, ConstNode &)
template<>
void append (const StringFeature &, Emitter &)
template<>
void fill (OptimizationArgBase &, ConstNode &)
template<>
void append (const OptimizationArgBase &, Emitter &)
template<>
void fill (OptimizationInfo &, ConstNode &)
template<>
void append (const OptimizationInfo &, Emitter &)
template<>
void fill (OptimizationSequence &, ConstNode &)
template<>
void append (const OptimizationSequence &, Emitter &)
template<>
void fill (StringFeature &Sf, ConstNode &Node)
template<>
void append (const StringFeature &Sf, Emitter &E)
template<>
void fill (OptimizationArgBase &OptArg, ConstNode &Node)
template<>
void append (const OptimizationArgBase &OptArg, Emitter &E)
template<>
void fill (OptimizationInfo &Info, ConstNode &Node)
template<>
void append (const OptimizationInfo &Info, Emitter &E)
template<>
void fill (OptimizationSequence &OSeq, ConstNode &Node)
template<>
void append (const OptimizationSequence &OSeq, Emitter &E)
template<>
void fill (void *&Vd, ConstNode &Node)
template<>
void append (void *const &Vd, Emitter &E)
Static Public Member Functions
static YAML::Node loadFile (std::string Filename)
template<class T >
static std::unique_ptr< T > get (ConstNode &Node)
Creates a new object of class T , by parsing a YAML::Node, and returning an std::unique_ptr of it.
template<class T >
static void fill (T &Value, ConstNode &Node)
Parses the node Node, and stores the information inside Value.
template<class T >
static void append (const T &Value, Emitter &E)
Appends the information of Value to the YAML::Emitter E.
template<class T >
static void print (const T &Value, std::ostream &Out=std::cout)
Prints to an std::ostream object the information of Value.
template<class T >
static void fill (VectorFeature< T > &Value, ConstNode &Node)
template<class T , class U >
static void fill (MapFeature< T, U > &Value, ConstNode &Node)
template<class T , class U >
static void fill (MapVectorFeature< T, U > &Value, ConstNode &Node)
template<class T >
static void fill (Formula< T > &Value, ConstNode &Node)
template<class T >
static void fill (ArithBinOpFormula< T > &Value, ConstNode &Node)
template<class T >
static void fill (BoolBinOpFormula< T > &Value, ConstNode &Node)
template<class T >
static void fill (IfFormula< T > &Value, ConstNode &Node)
template<class T >
static void fill (LitFormula< T > &Value, ConstNode &Node)
template<class T >
static void fill (FeatureFormula< T > &Value, ConstNode &Node)
template<class T , class U >
static void fill (SerialSet< T, U > &Value, ConstNode &Node)
template<class T >
static void append (const VectorFeature< T > &Value, Emitter &E)
template<class T , class U >
static void append (const MapFeature< T, U > &Value, Emitter &E)
template<class T , class U >
static void append (const MapVectorFeature< T, U > &Value, Emitter &E)
template<class T >
static void append (const Formula< T > &Value, Emitter &E)
template<class T >
static void append (const ArithBinOpFormula< T > &Value, Emitter &E)
template<class T >
static void append (const BoolBinOpFormula< T > &Value, Emitter &E)
template<class T >
static void append (const IfFormula< T > &Value, Emitter &E)
template<class T >
static void append (const LitFormula< T > &Value, Emitter &E)
template<class T >
static void append (const FeatureFormula< T > &Value, Emitter &E)
template<class T , class U >
static void append (const SerialSet< T, U > &Value, Emitter &E)
Detailed Description
This class is a wrapper class for the yaml-cpp library.
Definition at line 48 of file YAMLWrapper.h.
Member Typedef Documentation
typedef const YAML::Node pinhao::YAMLWrapper::ConstNode
Definition at line 50 of file YAMLWrapper.h.
typedef YAML::Emitter pinhao::YAMLWrapper::Emitter
Definition at line 51 of file YAMLWrapper.h.
Member Function Documentation
template<> void pinhao::YAMLWrapper::append (const StringFeature & Sf, Emitter & E)
Definition at line 22 of file FeatureYAMLWrapper.cpp.
template<> void pinhao::YAMLWrapper::append (void *const & Vd, Emitter & E)
Definition at line 26 of file YAMLWrapper.cpp.
template<class Type > void pinhao::YAMLWrapper::append (const VectorFeature< Type > & Vf, Emitter & E)
Definition at line 41 of file FeatureYAMLWrapper.h.
References pinhao::Feature::getName().
template<> void pinhao::YAMLWrapper::append (const OptimizationArgBase & OptArg, Emitter & E)
Definition at line 43 of file OptimizerYAMLWrapper.cpp.
References append(), pinhao::Bool, pinhao::Float, pinhao::Int, and pinhao::String.
void pinhao::YAMLWrapper::append (const Candidate & Cand, Emitter & E)
Definition at line 83 of file Candidate.cpp.
References append(), pinhao::Candidate::Count, and pinhao::Candidate::Score.
template<class KType , class VType > void pinhao::YAMLWrapper::append (const MapFeature< KType, VType > & Mf, Emitter & E)
Definition at line 77 of file FeatureYAMLWrapper.h.
References pinhao::MapFeature< KeyType, ElemType >::beginKeys(), pinhao::MapFeature< KeyType, ElemType >::endKeys(), pinhao::Feature::getDescription(), pinhao::Feature::getName(), and pinhao::MapFeature< KeyType, ElemType >::getValueOfKey().
template<> void pinhao::YAMLWrapper::append (const OptimizationInfo & Info, Emitter & E)
Definition at line 81 of file OptimizerYAMLWrapper.cpp.
References append().
template<class T > static void pinhao::YAMLWrapper::append (const T & Value, Emitter & E) inline static
Appends the information of Value to the YAML::Emitter E.
Definition at line 81 of file YAMLWrapper.h.
template<> void pinhao::YAMLWrapper::append (const OptimizationSequence & OSeq, Emitter & E)
Definition at line 107 of file OptimizerYAMLWrapper.cpp.
References append().
template<class KType , class VType > void pinhao::YAMLWrapper::append (const MapVectorFeature< KType, VType > & Mvf, Emitter & E)
Definition at line 119 of file FeatureYAMLWrapper.h.
References pinhao::MapVectorFeature< KeyType, ElemType >::beginKeys(), pinhao::MapVectorFeature< KeyType, ElemType >::endKeys(), and pinhao::Feature::getName().
template<class T > static void pinhao::YAMLWrapper::append (const VectorFeature< T > & Value, Emitter & E) static
template<class T , class U > static void pinhao::YAMLWrapper::append (const MapFeature< T, U > & Value, Emitter & E) static
template<class T , class U > static void pinhao::YAMLWrapper::append (const MapVectorFeature< T, U > & Value, Emitter & E) static
template<class T > void YAMLWrapper::append (const Formula< T > & Value, Emitter & E) static
Definition at line 59 of file FormulaYAMLWrapper.h.
References append(), pinhao::ArithBinOp, pinhao::Bool, pinhao::BoolBinOp, pinhao::Feature, pinhao::Float, pinhao::FormulaBase::getKind(), pinhao::Formula< T >::getOperandsType(), pinhao::If, pinhao::Int, pinhao::Literal, and pinhao::String.
template<class T > void YAMLWrapper::append (const ArithBinOpFormula< T > & Value, Emitter & E) static
Definition at line 107 of file FormulaYAMLWrapper.h.
References append(), pinhao::getFormulaKindString(), pinhao::ArithBinOpFormula< T >::getKind(), pinhao::BinOpFormulaBase< T, T >::getOperator(), pinhao::getOperatorKindString(), pinhao::ArithBinOpFormula< T >::getType(), pinhao::BinOpFormulaBase< T, T >::Lhs, and pinhao::BinOpFormulaBase< T, T >::Rhs.
template<class T > void YAMLWrapper::append (const BoolBinOpFormula< T > & Value, Emitter & E) static
Definition at line 134 of file FormulaYAMLWrapper.h.
References append(), pinhao::getFormulaKindString(), pinhao::BoolBinOpFormula< T >::getKind(), pinhao::BinOpFormulaBase< bool, T >::getOperandsType(), pinhao::BinOpFormulaBase< bool, T >::getOperator(), pinhao::getOperatorKindString(), pinhao::BoolBinOpFormula< T >::getType(), pinhao::BinOpFormulaBase< bool, T >::Lhs, and pinhao::BinOpFormulaBase< bool, T >::Rhs.
template<class T > void YAMLWrapper::append (const IfFormula< T > & Value, Emitter & E) static
Definition at line 163 of file FormulaYAMLWrapper.h.
References append(), pinhao::IfFormula< T >::Condition, pinhao::IfFormula< T >::ElseBody, pinhao::getFormulaKindString(), pinhao::IfFormula< T >::getKind(), pinhao::IfFormula< T >::getType(), and pinhao::IfFormula< T >::ThenBody.
template<class T > void YAMLWrapper::append (const LitFormula< T > & Value, Emitter & E) static
Definition at line 188 of file FormulaYAMLWrapper.h.
References append(), pinhao::getFormulaKindString(), pinhao::LitFormula< T >::getKind(), pinhao::LitFormula< T >::getType(), and pinhao::Formula< T >::getValue().
template<class T > void YAMLWrapper::append (const FeatureFormula< T > & Value, Emitter & E) static
Definition at line 213 of file FormulaYAMLWrapper.h.
References append(), pinhao::FeatureFormula< T >::FeaturePair, pinhao::getFormulaKindString(), pinhao::FeatureFormula< T >::getKind(), and pinhao::FeatureFormula< T >::getType().
template<class T , class U > void pinhao::YAMLWrapper::append (const SerialSet< T, U > & Value, Emitter & E) static
Definition at line 20 of file SerialSetYAMLWrapper.h.
References append().
void YAMLWrapper::append (const FormulaBase & Value, Emitter & E)
Definition at line 41 of file FormulaYAMLWrapper.cpp.
References append(), pinhao::Bool, pinhao::Float, pinhao::FormulaBase::getType(), pinhao::Int, and pinhao::String.
template<> void pinhao::YAMLWrapper::append (void *const & , Emitter &)
template<> void pinhao::YAMLWrapper::append (const StringFeature & , Emitter &)
template<> void pinhao::YAMLWrapper::append (const OptimizationArgBase & , Emitter &)
template<> void pinhao::YAMLWrapper::append (const OptimizationInfo & , Emitter &)
template<> void pinhao::YAMLWrapper::append (const OptimizationSequence & , Emitter &)
template<> void pinhao::YAMLWrapper::fill (StringFeature & Sf, ConstNode & Node)
Definition at line 17 of file FeatureYAMLWrapper.cpp.
template<> void pinhao::YAMLWrapper::fill (void *& Vd, ConstNode & Node)
Definition at line 22 of file YAMLWrapper.cpp.
template<> void pinhao::YAMLWrapper::fill (OptimizationArgBase & OptArg, ConstNode & Node)
Definition at line 25 of file OptimizerYAMLWrapper.cpp.
References pinhao::Bool, pinhao::Float, pinhao::Int, and pinhao::String.
template<class Type > void pinhao::YAMLWrapper::fill (VectorFeature< Type > & Vf, ConstNode & Node)
Definition at line 30 of file FeatureYAMLWrapper.h.
References pinhao::VectorFeature< ElemType >::setValueOf().
void pinhao::YAMLWrapper::fill (Candidate & Cand, ConstNode & Node)
Definition at line 102 of file Candidate.cpp.
References pinhao::Candidate::Count, and pinhao::Candidate::Score.
template<class KType , class VType > void pinhao::YAMLWrapper::fill (MapFeature< KType, VType > & Mf, ConstNode & Node)
Definition at line 64 of file FeatureYAMLWrapper.h.
References pinhao::Feature::getName(), and pinhao::MapFeature< KeyType, ElemType >::setValueOfKey().
template<> void pinhao::YAMLWrapper::fill (OptimizationInfo & Info, ConstNode & Node)
Definition at line 71 of file OptimizerYAMLWrapper.cpp.
References fill(), and pinhao::getOptimization().
template<class T > static void pinhao::YAMLWrapper::fill (T & Value, ConstNode & Node) inline static
Parses the node Node, and stores the information inside Value.
Definition at line 73 of file YAMLWrapper.h.
template<class T > static void pinhao::YAMLWrapper::fill (VectorFeature< T > & Value, ConstNode & Node) static
template<> void pinhao::YAMLWrapper::fill (OptimizationSequence & OSeq, ConstNode & Node)
Definition at line 99 of file OptimizerYAMLWrapper.cpp.
References fill().
template<class T , class U > static void pinhao::YAMLWrapper::fill (MapFeature< T, U > & Value, ConstNode & Node) static
template<class T , class U > static void pinhao::YAMLWrapper::fill (MapVectorFeature< T, U > & Value, ConstNode & Node) static
template<class KType , class VType > void pinhao::YAMLWrapper::fill (MapVectorFeature< KType, VType > & Mvf, ConstNode & Node)
Definition at line 102 of file FeatureYAMLWrapper.h.
References pinhao::MapVectorFeature< KeyType, ElemType >::setValueOfKey().
template<class T > void YAMLWrapper::fill (Formula< T > & Value, ConstNode & Node) static
Definition at line 23 of file FormulaYAMLWrapper.h.
References pinhao::ArithBinOp, pinhao::Bool, pinhao::BoolBinOp, pinhao::Feature, fill(), pinhao::Float, pinhao::FormulaBase::getKind(), pinhao::Formula< T >::getOperandsType(), pinhao::If, pinhao::Int, pinhao::Literal, and pinhao::String.
template<class T > void YAMLWrapper::fill (ArithBinOpFormula< T > & Value, ConstNode & Node) static
Definition at line 100 of file FormulaYAMLWrapper.h.
References pinhao::getOperatorKind(), pinhao::BinOpFormulaBase< T, T >::Lhs, pinhao::BinOpFormulaBase< T, T >::Rhs, and pinhao::BinOpFormulaBase< T, T >::setOperator().
template<class T > void YAMLWrapper::fill (BoolBinOpFormula< T > & Value, ConstNode & Node) static
Definition at line 127 of file FormulaYAMLWrapper.h.
References pinhao::getOperatorKind(), pinhao::BinOpFormulaBase< bool, T >::Lhs, pinhao::BinOpFormulaBase< bool, T >::Rhs, and pinhao::BinOpFormulaBase< bool, T >::setOperator().
template<class T > void YAMLWrapper::fill (IfFormula< T > & Value, ConstNode & Node) static
Definition at line 156 of file FormulaYAMLWrapper.h.
References pinhao::IfFormula< T >::Condition, pinhao::IfFormula< T >::ElseBody, and pinhao::IfFormula< T >::ThenBody.
template<class T > void YAMLWrapper::fill (LitFormula< T > & Value, ConstNode & Node) static
Definition at line 183 of file FormulaYAMLWrapper.h.
References pinhao::LitFormula< T >::setValue().
template<class T > void YAMLWrapper::fill (FeatureFormula< T > & Value, ConstNode & Node) static
Definition at line 204 of file FormulaYAMLWrapper.h.
References pinhao::FeatureFormula< T >::FeaturePair.
template<class T , class U > void pinhao::YAMLWrapper::fill (SerialSet< T, U > & Value, ConstNode & Node) static
Definition at line 11 of file SerialSetYAMLWrapper.h.
References fill().
template<> void pinhao::YAMLWrapper::fill (void *& , ConstNode &)
template<> void pinhao::YAMLWrapper::fill (StringFeature & , ConstNode &)
template<> void pinhao::YAMLWrapper::fill (OptimizationArgBase & , ConstNode &)
template<> void pinhao::YAMLWrapper::fill (OptimizationInfo & , ConstNode &)
template<> void pinhao::YAMLWrapper::fill (OptimizationSequence & , ConstNode &)
template<class T > static std::unique_ptr<T> pinhao::YAMLWrapper::get (ConstNode & Node) inline static
Creates a new object of class T , by parsing a YAML::Node, and returning an std::unique_ptr of it.
Definition at line 62 of file YAMLWrapper.h.
References fill().
std::unique_ptr< FormulaBase > YAMLWrapper::get (ConstNode & Node)
Definition at line 19 of file FormulaYAMLWrapper.cpp.
References pinhao::Bool, pinhao::createFormula(), fill(), pinhao::Float, pinhao::getFormulaKind(), pinhao::Int, and pinhao::String.
static YAML::Node pinhao::YAMLWrapper::loadFile (std::string Filename) inline static
Definition at line 53 of file YAMLWrapper.h.
template<class T > static void pinhao::YAMLWrapper::print (const T & Value, std::ostream & Out = std::cout) inline static
Prints to an std::ostream object the information of Value.
Definition at line 89 of file YAMLWrapper.h.
References append(), and fill().