Pinhao: pinhao::PAPIWrapper Class Reference
pinhao::PAPIWrapper Class Reference
This is a wrapper of the PAPI tool.
#include <PAPIWrapper.h>
Public Types
typedef long long LLong
typedef std::vector< int > EventCodeVector
typedef std::vector< LLong > CounterVector
typedef std::vector< std::string > ArgVector
Static Public Member Functions
static std::pair< int, CounterVector > countEvents (llvm::Module &, EventCodeVector)
Counts specific events detailed by the user.
static std::pair< int, LLong > getTotalCycles (llvm::Module &)
Returns the total number of clocks.
static std::pair< int, LLong > getTotalInstructions (llvm::Module &)
Returns the total number of instructions completed.
static std::pair< int, CounterVector > countEvents (llvm::Module &, ArgVector, EventCodeVector)
Counts specific events detailed by the user. For execution that requires arguments.
static std::pair< int, LLong > getTotalCycles (llvm::Module &, ArgVector)
Returns the total number of clocks. For execution that requires arguments.
static std::pair< int, LLong > getTotalInstructions (llvm::Module &, ArgVector)
Returns the total number of instructions completed. For execution that requires arguments.
Static Private Member Functions
static void init ()
Initializes the papi library.
static int createEventSet ()
Creates an EventSet.
static bool codesAreValid (EventCodeVector)
Returns true if all the events inside the vector are valid (available).
static void addEvent (int, int)
Adds an event to an EventSet.
static bool addEvents (int, EventCodeVector)
Returns true if it successfuly added all events to an EventSet.
static int run (llvm::Module &, ArgVector, char *const *, int, long long *)
Runs the llvm::Module, while counting the events.
Detailed Description
This is a wrapper of the PAPI tool.
Definition at line 20 of file PAPIWrapper.h.
Member Typedef Documentation
typedef std::vector<std::string> pinhao::PAPIWrapper::ArgVector
Definition at line 25 of file PAPIWrapper.h.
typedef std::vector<LLong> pinhao::PAPIWrapper::CounterVector
Definition at line 24 of file PAPIWrapper.h.
typedef std::vector<int> pinhao::PAPIWrapper::EventCodeVector
Definition at line 23 of file PAPIWrapper.h.
typedef long long pinhao::PAPIWrapper::LLong
Definition at line 22 of file PAPIWrapper.h.
Member Function Documentation
void PAPIWrapper::addEvent (int EventSet, int Code) static private
Adds an event to an EventSet.
Definition at line 34 of file PAPIWrapper.cpp.
bool PAPIWrapper::addEvents (int EventSet, PAPIWrapper::EventCodeVector Codes) static private
Returns true if it successfuly added all events to an EventSet.
Definition at line 39 of file PAPIWrapper.cpp.
References addEvent(), and codesAreValid().
bool PAPIWrapper::codesAreValid (PAPIWrapper::EventCodeVector Codes) static private
Returns true if all the events inside the vector are valid (available).
Definition at line 16 of file PAPIWrapper.cpp.
std::pair< int, PAPIWrapper::CounterVector > PAPIWrapper::countEvents (llvm::Module & Module, PAPIWrapper::EventCodeVector Codes) static
Counts specific events detailed by the user.
Definition at line 66 of file PAPIWrapper.cpp.
std::pair< int, PAPIWrapper::CounterVector > PAPIWrapper::countEvents (llvm::Module & Module, PAPIWrapper::ArgVector Args, PAPIWrapper::EventCodeVector Codes) static
Counts specific events detailed by the user. For execution that requires arguments.
Definition at line 72 of file PAPIWrapper.cpp.
References addEvents(), createEventSet(), init(), and run().
int PAPIWrapper::createEventSet () static private
Creates an EventSet.
Definition at line 23 of file PAPIWrapper.cpp.
std::pair< int, PAPIWrapper::LLong > PAPIWrapper::getTotalCycles (llvm::Module & Module) static
Returns the total number of clocks.
Definition at line 91 of file PAPIWrapper.cpp.
std::pair< int, PAPIWrapper::LLong > PAPIWrapper::getTotalCycles (llvm::Module & Module, PAPIWrapper::ArgVector Args) static
Returns the total number of clocks. For execution that requires arguments.
Definition at line 96 of file PAPIWrapper.cpp.
References addEvent(), createEventSet(), init(), and run().
std::pair< int, PAPIWrapper::LLong > PAPIWrapper::getTotalInstructions (llvm::Module & Module) static
Returns the total number of instructions completed.
Definition at line 109 of file PAPIWrapper.cpp.
std::pair< int, PAPIWrapper::LLong > PAPIWrapper::getTotalInstructions (llvm::Module & Module, PAPIWrapper::ArgVector Args) static
Returns the total number of instructions completed. For execution that requires arguments.
Definition at line 114 of file PAPIWrapper.cpp.
References addEvent(), createEventSet(), init(), and run().
void PAPIWrapper::init () static private
Initializes the papi library.
Definition at line 11 of file PAPIWrapper.cpp.
int PAPIWrapper::run (llvm::Module & , ArgVector , char *const * , int , long long *) static private
Runs the llvm::Module, while counting the events.
Definition at line 48 of file PAPIWrapper.cpp.
References pinhao::JITExecutor::flushCache(), and pinhao::JITExecutor::run().