Pinhao: pinhao::MapFeature< KeyType, ElemType > Class Template Reference
pinhao::MapFeature< KeyType, ElemType > Class Template Reference
This class maps a KeyType to a ElemType feature.
#include <MapFeature.h>
Public Types
typedef StdMapKeyIterator< KeyType, ElemType > iterator
Public Types inherited from pinhao::Feature
typedef std::map< std::string, std::string >::iterator iterator
Public Member Functions
virtual ~MapFeature ()
MapFeature (FeatureInfo *Info)
virtual bool hasKey (const KeyType &Key) const override
Returns true if the key Key is mapped to some value.
void setValueOfKey (std::string FeatureName, ElemType Elem, KeyType Key) override
Sets the value of the feature FeatureName of the key Key to Value.
const ElemType & getValueOfKey (std::string FeatureName, const KeyType Key) const override
Returns the value of a feature that has name FeatureName and key Key.
KeyIterator< KeyType > & beginKeys () override
Returns the reference of the begin of an abstract iterator.
KeyIterator< KeyType > & endKeys () override
Returns the reference of the end of an abstract iterator.
virtual void append (YAML::Emitter &Emitter) const override
Appends to a YAML::Emitter this feature data.
virtual void get (const YAML::Node &Node) override
Gets the feature data from a YAML::Node.
Public Member Functions inherited from pinhao::MappedFeature< KeyType, ElemType >
virtual ~MappedFeature ()
MappedFeature (FeatureInfo *Info)
Public Member Functions inherited from pinhao::Feature
virtual ~Feature ()
Feature (FeatureInfo *InfoPtr, FeatureKind FKind)
Constructs a Feature with the information FeatInfo.
std::string getName () const
Gets the name of the feature.
std::string getDescription () const
Gets the description of the feature.
ValueType getType () const
Gets the ValueType of the feature.
uint64_t getNumberOfSubFeatures () const
Gets the description of the sub-feature with name SubFeatureName.
bool hasSubFeature (std::string SubFeatureName) const
Returns true if there is a sub-feature with name SubFeatureName.
std::string getSubFeatureDescription (std::string SubFeatureName) const
Gets the description of the sub-feature with name SubFeatureName.
FeatureKind getKind () const
Returns the FeatureKind.
bool isComposite () const
Returns true if the feature has more than two sub-features.
bool isProcessed () const
Returns true if the feature has already been processed.
bool isLinear () const
Returns true if it is a LinearFeature.
bool isMapped () const
Returns true if it is a MappedFeature.
bool isStaticFeature () const
Returns true if it is a static feature.
bool isDynamicFeature () const
Returns true if it is a dynamic feature.
iterator begin () const
Gets the begin iterator of the Info.
iterator end () const
Gets the end iterator of the Info.
void print (std::ostream &Out=std::cout)
Prints its information into a std::ostream object in the format yaml.
virtual void processModule (llvm::Module &Module)=0
Gets the necessary information from a llvm::Module.
virtual std::unique_ptr< Feature > clone () const =0
Clones the feature.
Protected Attributes
std::map< KeyType, ElemType > TheFeature
The vector container of the feature itself.
Protected Attributes inherited from pinhao::Feature
std::shared_ptr< FeatureInfo > Info
bool Processed
Detailed Description
template<class KeyType, class ElemType>
class pinhao::MapFeature< KeyType, ElemType >
This class maps a KeyType to a ElemType feature.
It is a composite feature type which maps a given KeyType to a vector of sub-features of type ElemType. So, every KeyType has all sub-feature values.
Definition at line 27 of file MapFeature.h.
Member Typedef Documentation
template<class KeyType, class ElemType> typedef StdMapKeyIterator<KeyType, ElemType> pinhao::MapFeature< KeyType, ElemType >::iterator
Definition at line 29 of file MapFeature.h.
Constructor & Destructor Documentation
template<class KeyType, class ElemType> virtual pinhao::MapFeature< KeyType, ElemType >::~MapFeature () inline virtual
Definition at line 36 of file MapFeature.h.
template<class KeyType, class ElemType> pinhao::MapFeature< KeyType, ElemType >::MapFeature (FeatureInfo * Info) inline
Definition at line 37 of file MapFeature.h.
References pinhao::MapFeature< KeyType, ElemType >::append(), pinhao::MapFeature< KeyType, ElemType >::beginKeys(), pinhao::MapFeature< KeyType, ElemType >::endKeys(), pinhao::MapFeature< KeyType, ElemType >::getValueOfKey(), pinhao::MapFeature< KeyType, ElemType >::hasKey(), and pinhao::MapFeature< KeyType, ElemType >::setValueOfKey().
Member Function Documentation
template<class KeyType , class ElemType > void MapFeature::append (YAML::Emitter & Emitter) const override virtual
Appends to a YAML::Emitter this feature data.
Parameters
Emitter The place where the data information will be appended.
Implements pinhao::Feature.
Definition at line 87 of file MapFeature.h.
References pinhao::YAMLWrapper::append().
template<class KeyType , class ElemType > KeyIterator< KeyType > & MapFeature::beginKeys () override virtual
Returns the reference of the begin of an abstract iterator.
Implements pinhao::MappedFeature< KeyType, ElemType >.
Definition at line 73 of file MapFeature.h.
References pinhao::MapFeature< KeyType, ElemType >::TheFeature.
template<class KeyType , class ElemType > KeyIterator< KeyType > & MapFeature::endKeys () override virtual
Returns the reference of the end of an abstract iterator.
Implements pinhao::MappedFeature< KeyType, ElemType >.
Definition at line 80 of file MapFeature.h.
References pinhao::MapFeature< KeyType, ElemType >::TheFeature.
template<class KeyType , class ElemType > void MapFeature::get (const YAML::Node & Node) override virtual
Gets the feature data from a YAML::Node.
Implements pinhao::Feature.
Definition at line 92 of file MapFeature.h.
References pinhao::YAMLWrapper::fill().
template<class KeyType , class ElemType > const ElemType & MapFeature::getValueOfKey (std::string FeatureName, const KeyType Key) const override virtual
Returns the value of a feature that has name FeatureName and key Key.
Implements pinhao::MappedFeature< KeyType, ElemType >.
Definition at line 67 of file MapFeature.h.
References pinhao::Feature::getName(), and pinhao::MapFeature< KeyType, ElemType >::TheFeature.
template<class KeyType , class ElemType > bool MapFeature::hasKey (const KeyType & Key) const override virtual
Returns true if the key Key is mapped to some value.
Implements pinhao::MappedFeature< KeyType, ElemType >.
Definition at line 56 of file MapFeature.h.
References pinhao::MapFeature< KeyType, ElemType >::TheFeature.
template<class KeyType , class ElemType > void MapFeature::setValueOfKey (std::string FeatureName, ElemType Value, KeyType Key) override virtual
Sets the value of the feature FeatureName of the key Key to Value.
Implements pinhao::MappedFeature< KeyType, ElemType >.
Definition at line 61 of file MapFeature.h.
References pinhao::Feature::getName(), and pinhao::MapFeature< KeyType, ElemType >::TheFeature.
Member Data Documentation
template<class KeyType, class ElemType> std::map<KeyType, ElemType> pinhao::MapFeature< KeyType, ElemType >::TheFeature protected
The vector container of the feature itself.
Definition at line 33 of file MapFeature.h.