Pinhao: pinhao::SimpleGrammarEvolution Class Reference
pinhao::SimpleGrammarEvolution Class Reference
This is a simple implementation of the GrammarEvolution class.
#include <SimpleGrammarEvolution.h>
Public Member Functions
virtual ~SimpleGrammarEvolution ()
SimpleGrammarEvolution (std::shared_ptr< llvm::Module >, std::string="config.yaml", double=0.2, double=0.3, double=0.3)
virtual void run (int, int, std::shared_ptr< FeatureSet >) override
By default, is the function that starts the execution of the algorithm.
virtual void stop () override
By default, is the function that ends the execution of the algorithm.
Public Member Functions inherited from pinhao::GrammarEvolution< Candidate >
virtual ~GrammarEvolution ()
GrammarEvolution (std::shared_ptr< llvm::Module >, std::string="config.yaml", double=0.2, double=0.3, double=0.3)
Private Member Functions
virtual llvm::Module * compileWithCandidate (llvm::Module *, Candidate &, FeatureSet *) override
Depends on the DecisionPoint's added. As it changes, the way to compile the module also changes.
Additional Inherited Members
Protected Member Functions inherited from pinhao::GrammarEvolution< Candidate >
virtual void addPreDefinedDecisionPoints ()
Adds some pre-defined decision points.
virtual void importKnowledgeBase ()
Imports the knowledge base that is inside the file KnowledgeBaseFile.
virtual void exportKnowledgeBase ()
Exports the knowledge base to the file KnowledgeBaseFile.
Protected Attributes inherited from pinhao::GrammarEvolution< Candidate >
std::shared_ptr< llvm::Module > Module
std::string KnowledgeBaseFile
double EvolveProbability
double MaxEvolutionRate
double MutateProbability
std::vector< DecisionPoint > DecisionPoints
SerialSet< Candidate > KnowledgeBase
Detailed Description
This is a simple implementation of the GrammarEvolution class.
It uses all default implementations, and also implements a simple run and stop function.
Definition at line 24 of file SimpleGrammarEvolution.h.
Constructor & Destructor Documentation
SimpleGrammarEvolution::~SimpleGrammarEvolution () virtual
Definition at line 66 of file SimpleGrammarEvolution.cpp.
SimpleGrammarEvolution::SimpleGrammarEvolution (std::shared_ptr< llvm::Module > Module, std::string KBFilename = "config.yaml", double EvolveProb = 0.2, double MaxEvolutionRate = 0.3, double MutateProb = 0.3)
Definition at line 70 of file SimpleGrammarEvolution.cpp.
References compileWithCandidate().
Member Function Documentation
llvm::Module * pinhao::SimpleGrammarEvolution::compileWithCandidate (llvm::Module * , Candidate & , FeatureSet *) override private virtual
Depends on the DecisionPoint's added. As it changes, the way to compile the module also changes.
Implements pinhao::GrammarEvolution< Candidate >.
Definition at line 77 of file SimpleGrammarEvolution.cpp.
References pinhao::OptimizationSet::addOptimization(), pinhao::applyOptimizations(), pinhao::getOptimization(), and pinhao::FormulaBase::solveFor().
void pinhao::SimpleGrammarEvolution::run (int , int , std::shared_ptr< FeatureSet >) override virtual
By default, is the function that starts the execution of the algorithm.
Implements pinhao::GrammarEvolution< Candidate >.
Definition at line 94 of file SimpleGrammarEvolution.cpp.
References pinhao::GrammarEvolution< Candidate >::addPreDefinedDecisionPoints(), pinhao::Candidate::clone(), compileWithCandidate(), pinhao::Candidate::Count, pinhao::GrammarEvolution< Candidate >::DecisionPoints, pinhao::GrammarEvolution< Candidate >::EvolveProbability, pinhao::UniformRandom::getRandomReal(), pinhao::PAPIWrapper::getTotalCycles(), pinhao::GrammarEvolution< Candidate >::importKnowledgeBase(), pinhao::GrammarEvolution< Candidate >::KnowledgeBase, pinhao::GrammarEvolution< Candidate >::MaxEvolutionRate, pinhao::GrammarEvolution< Candidate >::Module, pinhao::GrammarEvolution< Candidate >::MutateProbability, pinhao::Candidate::Score, and stop().
void pinhao::SimpleGrammarEvolution::stop () override virtual
By default, is the function that ends the execution of the algorithm.
Implements pinhao::GrammarEvolution< Candidate >.
Definition at line 178 of file SimpleGrammarEvolution.cpp.
References pinhao::GrammarEvolution< Candidate >::exportKnowledgeBase().