Pinhao: pinhao::MapVectorFeature< KeyType, ElemType > Class Template Reference
pinhao::MapVectorFeature< KeyType, ElemType > Class Template Reference
This class maps a KeyType to a vector of ElemType features.
#include <MapVectorFeature.h>
Public Types
typedef StdMapKeyIterator< KeyType, std::vector< ElemType > > iterator
Public Types inherited from pinhao::Feature
typedef std::map< std::string, std::string >::iterator iterator
Public Member Functions
virtual ~MapVectorFeature ()
MapVectorFeature (FeatureInfo *Info)
virtual bool hasKey (const KeyType &Key) const override
Returns true if the key Key is mapped to some value.
void setValueOfKey (std::string FeatureName, ElemType Elem, KeyType Key) override
Sets the value of the sub-feature, with name FeatureName, of key Key, to value Elem.
const ElemType & getValueOfKey (std::string FeatureName, const KeyType Key) const override
Gets the sub-feature value, whose name is FeatureName, and type ElemType.
KeyIterator< KeyType > & beginKeys () override
Returns the reference of the begin of an abstract iterator.
KeyIterator< KeyType > & endKeys () override
Returns the reference of the end of an abstract iterator.
virtual void append (YAML::Emitter &Emitter) const override
Appends to a YAML::Emitter this feature data.
virtual void get (const YAML::Node &Node) override
Gets the feature data from a YAML::Node.
Public Member Functions inherited from pinhao::MappedFeature< KeyType, ElemType >
virtual ~MappedFeature ()
MappedFeature (FeatureInfo *Info)
Public Member Functions inherited from pinhao::Feature
virtual ~Feature ()
Feature (FeatureInfo *InfoPtr, FeatureKind FKind)
Constructs a Feature with the information FeatInfo.
std::string getName () const
Gets the name of the feature.
std::string getDescription () const
Gets the description of the feature.
ValueType getType () const
Gets the ValueType of the feature.
uint64_t getNumberOfSubFeatures () const
Gets the description of the sub-feature with name SubFeatureName.
bool hasSubFeature (std::string SubFeatureName) const
Returns true if there is a sub-feature with name SubFeatureName.
std::string getSubFeatureDescription (std::string SubFeatureName) const
Gets the description of the sub-feature with name SubFeatureName.
FeatureKind getKind () const
Returns the FeatureKind.
bool isComposite () const
Returns true if the feature has more than two sub-features.
bool isProcessed () const
Returns true if the feature has already been processed.
bool isLinear () const
Returns true if it is a LinearFeature.
bool isMapped () const
Returns true if it is a MappedFeature.
bool isStaticFeature () const
Returns true if it is a static feature.
bool isDynamicFeature () const
Returns true if it is a dynamic feature.
iterator begin () const
Gets the begin iterator of the Info.
iterator end () const
Gets the end iterator of the Info.
void print (std::ostream &Out=std::cout)
Prints its information into a std::ostream object in the format yaml.
virtual void processModule (llvm::Module &Module)=0
Gets the necessary information from a llvm::Module.
virtual std::unique_ptr< Feature > clone () const =0
Clones the feature.
Protected Member Functions
void initVectorOfKey (const KeyType Key)
Initializes the vector of the key at the map TheFeature.
Protected Attributes
std::map< KeyType, std::vector< ElemType > > TheFeature
The vector container of the feature itself.
Protected Attributes inherited from pinhao::Feature
std::shared_ptr< FeatureInfo > Info
bool Processed
Detailed Description
template<class KeyType, class ElemType>
class pinhao::MapVectorFeature< KeyType, ElemType >
This class maps a KeyType to a vector of ElemType features.
It is a composite feature type which maps a given KeyType to a vector of sub-features of type ElemType. So, every KeyType has all sub-feature values.
Definition at line 26 of file MapVectorFeature.h.
Member Typedef Documentation
template<class KeyType, class ElemType> typedef StdMapKeyIterator<KeyType, std::vector<ElemType> > pinhao::MapVectorFeature< KeyType, ElemType >::iterator
Definition at line 28 of file MapVectorFeature.h.
Constructor & Destructor Documentation
template<class KeyType, class ElemType> virtual pinhao::MapVectorFeature< KeyType, ElemType >::~MapVectorFeature () inline virtual
Definition at line 42 of file MapVectorFeature.h.
template<class KeyType, class ElemType> pinhao::MapVectorFeature< KeyType, ElemType >::MapVectorFeature (FeatureInfo * Info) inline
Definition at line 44 of file MapVectorFeature.h.
References pinhao::MapVectorFeature< KeyType, ElemType >::append(), pinhao::MapVectorFeature< KeyType, ElemType >::beginKeys(), pinhao::MapVectorFeature< KeyType, ElemType >::endKeys(), pinhao::MapVectorFeature< KeyType, ElemType >::getValueOfKey(), pinhao::MapVectorFeature< KeyType, ElemType >::hasKey(), pinhao::Feature::isComposite(), and pinhao::MapVectorFeature< KeyType, ElemType >::setValueOfKey().
Member Function Documentation
template<class KeyType , class ElemType > void MapVectorFeature::append (YAML::Emitter & Emitter) const override virtual
Appends to a YAML::Emitter this feature data.
Parameters
Emitter The place where the data information will be appended.
Implements pinhao::Feature.
Definition at line 124 of file MapVectorFeature.h.
References pinhao::YAMLWrapper::append().
template<class KeyType , class ElemType > KeyIterator< KeyType > & MapVectorFeature::beginKeys () override virtual
Returns the reference of the begin of an abstract iterator.
Implements pinhao::MappedFeature< KeyType, ElemType >.
Definition at line 110 of file MapVectorFeature.h.
References pinhao::MapVectorFeature< KeyType, ElemType >::TheFeature.
template<class KeyType , class ElemType > KeyIterator< KeyType > & MapVectorFeature::endKeys () override virtual
Returns the reference of the end of an abstract iterator.
Implements pinhao::MappedFeature< KeyType, ElemType >.
Definition at line 117 of file MapVectorFeature.h.
References pinhao::MapVectorFeature< KeyType, ElemType >::TheFeature.
template<class KeyType , class ElemType > void MapVectorFeature::get (const YAML::Node & Node) override virtual
Gets the feature data from a YAML::Node.
Implements pinhao::Feature.
Definition at line 129 of file MapVectorFeature.h.
References pinhao::YAMLWrapper::fill().
template<class KeyType , class ElemType > const ElemType & MapVectorFeature::getValueOfKey (std::string FeatureName, const KeyType Key) const override virtual
Gets the sub-feature value, whose name is FeatureName, and type ElemType.
As it is a map, it should be provided the Key of type KeyType, so that it is returned the pointer to the sub-feature of that key.
Parameters
FeatureName The name of the sub-feature.
Key The key to get from.
Returns
A const pointer to the value of the sub-feature of the key.
Implements pinhao::MappedFeature< KeyType, ElemType >.
Definition at line 100 of file MapVectorFeature.h.
References pinhao::CompositeFeatureInfo::getIndexOfSubFeature(), pinhao::MapVectorFeature< KeyType, ElemType >::hasKey(), pinhao::Feature::hasSubFeature(), pinhao::Feature::Info, and pinhao::MapVectorFeature< KeyType, ElemType >::TheFeature.
template<class KeyType , class ElemType > bool MapVectorFeature::hasKey (const KeyType & Key) const override virtual
Returns true if the key Key is mapped to some value.
Implements pinhao::MappedFeature< KeyType, ElemType >.
Definition at line 85 of file MapVectorFeature.h.
References pinhao::MapVectorFeature< KeyType, ElemType >::TheFeature.
template<class KeyType, class ElemType> void pinhao::MapVectorFeature< KeyType, ElemType >::initVectorOfKey (const KeyType Key) inline protected
Initializes the vector of the key at the map TheFeature.
Definition at line 35 of file MapVectorFeature.h.
References pinhao::CompositeFeatureInfo::getNumberOfSubFeatures(), pinhao::MapVectorFeature< KeyType, ElemType >::hasKey(), and pinhao::Feature::Info.
template<class KeyType , class ElemType > void MapVectorFeature::setValueOfKey (std::string FeatureName, ElemType Elem, KeyType Key) override virtual
Sets the value of the sub-feature, with name FeatureName, of key Key, to value Elem.
Parameters
FeatureName The name of the sub-feature.
Elem The value that will replace the old one.
Key The key from which it will set the sub-feature value.
Implements pinhao::MappedFeature< KeyType, ElemType >.
Definition at line 90 of file MapVectorFeature.h.
References pinhao::CompositeFeatureInfo::getIndexOfSubFeature(), pinhao::Feature::hasSubFeature(), pinhao::Feature::Info, pinhao::MapVectorFeature< KeyType, ElemType >::initVectorOfKey(), and pinhao::MapVectorFeature< KeyType, ElemType >::TheFeature.
Member Data Documentation
template<class KeyType, class ElemType> std::map<KeyType, std::vector<ElemType> > pinhao::MapVectorFeature< KeyType, ElemType >::TheFeature protected
The vector container of the feature itself.
Definition at line 32 of file MapVectorFeature.h.