Pinhao: pinhao::FeatureRegistry Class Reference
pinhao::FeatureRegistry Class Reference
This class contains all registered features as well as its manipulation methods.
#include <FeatureRegistry.h>
Public Types
typedef std::map< std::string, std::unique_ptr< const Feature > > FeaturesMap
Static Public Member Functions
static void registerFeature (Feature *F)
Register a feature in order to become available.
static std::unique_ptr< Feature > get (std::string FeatureName)
Clones a feature with name FeatureName and returns it.
Static Private Member Functions
static FeaturesMap & getRegisteredFeatures ()
Gets a map that stores unique pointers to all registered features.
Detailed Description
This class contains all registered features as well as its manipulation methods.
When a RegisterFeature variable is created it calls a static method of this class in order to insert the new feature in the registry. It is the container of all registered features.
Definition at line 27 of file FeatureRegistry.h.
Member Typedef Documentation
typedef std::map<std::string, std::unique_ptr<const Feature> > pinhao::FeatureRegistry::FeaturesMap
Definition at line 29 of file FeatureRegistry.h.
Member Function Documentation
std::unique_ptr< Feature > FeatureRegistry::get (std::string FeatureName) static
Clones a feature with name FeatureName and returns it.
Search the RegisteredFeatures for a feature with name FeatureName. If it finds the feature, then it return the feature's clone. Else, it will return a unique_ptr to nullptr.
Parameters
FeatureName The name of the feature.
Returns
A unique pointer with a clone of the feature (if found).
Definition at line 30 of file FeatureRegistry.cpp.
References getRegisteredFeatures().
FeaturesMap & FeatureRegistry::getRegisteredFeatures () static private
Gets a map that stores unique pointers to all registered features.
In order to use a registered feature, one should clone the desired feature. It maps the name to the feature.
Definition at line 16 of file FeatureRegistry.cpp.
void FeatureRegistry::registerFeature (Feature * F) static
Register a feature in order to become available.
Definition at line 21 of file FeatureRegistry.cpp.
References pinhao::Feature::getName(), and getRegisteredFeatures().