Pinhao: pinhao::KeyIterator< KType > Class Template Reference
pinhao::KeyIterator< KType > Class Template Reference abstract
Base class for iterating over the keys of some MappedFeature.
#include <Features.h>
Public Member Functions
virtual ~KeyIterator ()
virtual const KType * operator-> () const =0
virtual const KType & operator* ()=0
virtual KeyIterator & operator++ ()=0
It will return a reference, as it can't be instantiated.
virtual bool operator== (const KeyIterator &It)=0
virtual bool operator!= (const KeyIterator &It)=0
Detailed Description
template<class KType>
class pinhao::KeyIterator< KType >
Base class for iterating over the keys of some MappedFeature.
Definition at line 16 of file Features.h.
Constructor & Destructor Documentation
template<class KType> virtual pinhao::KeyIterator< KType >::~KeyIterator () inline virtual
Definition at line 23 of file Iterator.h.
References pinhao::KeyIterator< KType >::operator!=(), pinhao::KeyIterator< KType >::operator*(), pinhao::KeyIterator< KType >::operator++(), pinhao::KeyIterator< KType >::operator->(), and pinhao::KeyIterator< KType >::operator==().
Member Function Documentation
template<class KType> virtual bool pinhao::KeyIterator< KType >::operator!= (const KeyIterator< KType > & It) pure virtual
Implemented in pinhao::StdMapKeyIterator< KType, VType >.
template<class KType> virtual const KType& pinhao::KeyIterator< KType >::operator* () pure virtual
Implemented in pinhao::StdMapKeyIterator< KType, VType >.
template<class KType> virtual KeyIterator& pinhao::KeyIterator< KType >::operator++ () pure virtual
It will return a reference, as it can't be instantiated.
Implemented in pinhao::StdMapKeyIterator< KType, VType >.
template<class KType> virtual const KType* pinhao::KeyIterator< KType >::operator-> () const pure virtual
Implemented in pinhao::StdMapKeyIterator< KType, VType >.
template<class KType> virtual bool pinhao::KeyIterator< KType >::operator== (const KeyIterator< KType > & It) pure virtual
Implemented in pinhao::StdMapKeyIterator< KType, VType >.