Pinhao: pinhao::SProfWrapper Class Reference
pinhao::SProfWrapper Class Reference
This class is a wrapper of the StaticProfiler tool.
#include <SProfWrapper.h>
Public Types
typedef std::shared_ptr< llvm::StaticFunctionCost > StaticFunctionCostPtr
typedef std::map< llvm::Function *, double > CostMap
Static Public Member Functions
static double getFunctionCost (llvm::Module &, llvm::Function &)
Gets a llvm::Function cost.
static double getModuleCost (llvm::Module &)
Returns the sum of all @ llvm::Functions from the llvm::Module.
static CostMap getAllFunctionsCost (llvm::Module &)
Returns the cost of each llvm::Function.
Static Private Member Functions
static llvm::Pass * getSProfPass (StaticFunctionCostPtr)
Creates the StaticProfiler main llvm::Pass.
static double sumAllFunctionsCost (CostMap &)
Sums all function costs.
Detailed Description
This class is a wrapper of the StaticProfiler tool.
It calculates, statically, the cost of each llvm::Function. For the llvm::Module, it sums up all its llvm::Function costs.
Definition at line 25 of file SProfWrapper.h.
Member Typedef Documentation
typedef std::map<llvm::Function*, double> pinhao::SProfWrapper::CostMap
Definition at line 28 of file SProfWrapper.h.
typedef std::shared_ptr<llvm::StaticFunctionCost> pinhao::SProfWrapper::StaticFunctionCostPtr
Definition at line 27 of file SProfWrapper.h.
Member Function Documentation
SProfWrapper::CostMap SProfWrapper::getAllFunctionsCost (llvm::Module & Module) static
Returns the cost of each llvm::Function.
Definition at line 36 of file SProfWrapper.cpp.
References getSProfPass().
double SProfWrapper::getFunctionCost (llvm::Module & Module, llvm::Function & Function) static
Gets a llvm::Function cost.
Definition at line 23 of file SProfWrapper.cpp.
References getSProfPass().
double SProfWrapper::getModuleCost (llvm::Module & Module) static
Returns the sum of all @ llvm::Functions from the llvm::Module.
Definition at line 31 of file SProfWrapper.cpp.
References getAllFunctionsCost(), and sumAllFunctionsCost().
llvm::Pass * SProfWrapper::getSProfPass (StaticFunctionCostPtr SFC) static private
Creates the StaticProfiler main llvm::Pass.
Definition at line 12 of file SProfWrapper.cpp.
double SProfWrapper::sumAllFunctionsCost (SProfWrapper::CostMap & Map) static private
Sums all function costs.
Definition at line 16 of file SProfWrapper.cpp.