Pinhao: pinhao::OptimizationSequence Class Reference
pinhao::OptimizationSequence Class Reference
Contains a sequence for a specific OptimizationSet.
#include <OptimizationSequence.h>
Public Member Functions
OptimizationSequence ()
void populatePassManager (llvm::legacy::PassManager &PM)
Populates a llvm::legacy::PassManager with the current Sequence.
OptimizationInfo getOptimization (uint64_t N)
Gets the OptimizationInfo of the Nth element of the sequence.
void print (std::ostream &Out=std::cout)
Prints to Out the information of this OptimizationSequence.
void populateFunctionPassManager (llvm::legacy::FunctionPassManager &FPM)
Populates a llvm::legacy::FunctionPassManager with the current Sequence.
Static Public Member Functions
static std::unique_ptr< OptimizationSequence > generate (OptimizationSet &Set, int Size=-1)
Generates a OptimizationSequence from a specified OptimizationSet.
static std::unique_ptr< OptimizationSequence > generate (std::vector< Optimization > Sequence)
Encapsulates a vector of Optimizations into a OptimizationSequence.
static std::unique_ptr< OptimizationSequence > randomize (uint64_t Size)
Generates a random sequence.
Detailed Description
Contains a sequence for a specific OptimizationSet.
Definition at line 24 of file OptimizationSequence.h.
Constructor & Destructor Documentation
pinhao::OptimizationSequence::OptimizationSequence () inline
Definition at line 26 of file OptimizationSequence.h.
References generate(), getOptimization(), populateFunctionPassManager(), populatePassManager(), print(), and randomize().
Member Function Documentation
std::unique_ptr< OptimizationSequence > OptimizationSequence::generate (OptimizationSet & Set, int Size = -1) static
Generates a OptimizationSequence from a specified OptimizationSet.
Definition at line 23 of file OptimizationSequence.cpp.
References OptimizationSequence(), and pinhao::OptimizationSet::size().
std::unique_ptr< OptimizationSequence > OptimizationSequence::generate (std::vector< Optimization > Sequence) static
Encapsulates a vector of Optimizations into a OptimizationSequence.
Definition at line 60 of file OptimizationSequence.cpp.
References OptimizationSequence().
OptimizationInfo OptimizationSequence::getOptimization (uint64_t N)
Gets the OptimizationInfo of the Nth element of the sequence.
Definition at line 85 of file OptimizationSequence.cpp.
void OptimizationSequence::populateFunctionPassManager (llvm::legacy::FunctionPassManager & FPM)
Populates a llvm::legacy::FunctionPassManager with the current Sequence.
Note that all the optimizations must be for functions (PassKind < 4).
Definition at line 95 of file OptimizationSequence.cpp.
void OptimizationSequence::populatePassManager (llvm::legacy::PassManager & PM)
Populates a llvm::legacy::PassManager with the current Sequence.
Definition at line 90 of file OptimizationSequence.cpp.
void OptimizationSequence::print (std::ostream & Out = std::cout)
Prints to Out the information of this OptimizationSequence.
Definition at line 103 of file OptimizationSequence.cpp.
References pinhao::YAMLWrapper::print().
std::unique_ptr< OptimizationSequence > OptimizationSequence::randomize (uint64_t Size) static
Generates a random sequence.
Definition at line 72 of file OptimizationSequence.cpp.
References OptimizationSequence().