Pinhao: pinhao::Feature Class Reference
pinhao::Feature Class Reference abstract
This is the base class for features.
#include <Feature.h>
Public Types
typedef std::map< std::string, std::string >::iterator iterator
Public Member Functions
virtual ~Feature ()
Feature (FeatureInfo *InfoPtr, FeatureKind FKind)
Constructs a Feature with the information FeatInfo.
std::string getName () const
Gets the name of the feature.
std::string getDescription () const
Gets the description of the feature.
ValueType getType () const
Gets the ValueType of the feature.
uint64_t getNumberOfSubFeatures () const
Gets the description of the sub-feature with name SubFeatureName.
bool hasSubFeature (std::string SubFeatureName) const
Returns true if there is a sub-feature with name SubFeatureName.
std::string getSubFeatureDescription (std::string SubFeatureName) const
Gets the description of the sub-feature with name SubFeatureName.
FeatureKind getKind () const
Returns the FeatureKind.
bool isComposite () const
Returns true if the feature has more than two sub-features.
bool isProcessed () const
Returns true if the feature has already been processed.
bool isLinear () const
Returns true if it is a LinearFeature.
bool isMapped () const
Returns true if it is a MappedFeature.
bool isStaticFeature () const
Returns true if it is a static feature.
bool isDynamicFeature () const
Returns true if it is a dynamic feature.
iterator begin () const
Gets the begin iterator of the Info.
iterator end () const
Gets the end iterator of the Info.
void print (std::ostream &Out=std::cout)
Prints its information into a std::ostream object in the format yaml.
virtual void append (YAML::Emitter &Emitter) const =0
Appends to a YAML::Emitter this feature data.
virtual void get (const YAML::Node &Node)=0
Gets the feature data from a YAML::Node.
virtual void processModule (llvm::Module &Module)=0
Gets the necessary information from a llvm::Module.
virtual std::unique_ptr< Feature > clone () const =0
Clones the feature.
Protected Attributes
std::shared_ptr< FeatureInfo > Info
bool Processed
Private Member Functions
CompositeFeatureInfo * getCompositeFeatureInfo () const
Casts Info to a CompositeFeatureInfo type, if possible.
Private Attributes
FeatureKind Kind
Detailed Description
This is the base class for features.
All new feature types must implement this class. So that they all can be registered.
Definition at line 37 of file Feature.h.
Member Typedef Documentation
typedef std::map<std::string, std::string>::iterator pinhao::Feature::iterator
Definition at line 39 of file Feature.h.
Constructor & Destructor Documentation
virtual pinhao::Feature::~Feature () inline virtual
Definition at line 52 of file Feature.h.
References pinhao::Feature.
Feature::Feature (FeatureInfo * InfoPtr, FeatureKind FKind)
Constructs a Feature with the information FeatInfo.
Definition at line 16 of file Feature.cpp.
References Processed.
Member Function Documentation
virtual void pinhao::Feature::append (YAML::Emitter & Emitter) const pure virtual
Appends to a YAML::Emitter this feature data.
Parameters
Emitter The place where the data information will be appended.
Implemented in pinhao::StringFeature, pinhao::MapVectorFeature< KeyType, ElemType >, pinhao::VectorFeature< ElemType >, and pinhao::MapFeature< KeyType, ElemType >.
Feature::iterator Feature::begin () const
Gets the begin iterator of the Info.
Definition at line 76 of file Feature.cpp.
References pinhao::CompositeFeatureInfo::begin(), and getCompositeFeatureInfo().
virtual std::unique_ptr<Feature> pinhao::Feature::clone () const pure virtual
Clones the feature.
Returns
A unique pointer to the clone Feature.
Feature::iterator Feature::end () const
Gets the end iterator of the Info.
Definition at line 80 of file Feature.cpp.
References pinhao::CompositeFeatureInfo::end(), and getCompositeFeatureInfo().
virtual void pinhao::Feature::get (const YAML::Node & Node) pure virtual
Gets the feature data from a YAML::Node.
Implemented in pinhao::StringFeature, pinhao::MapVectorFeature< KeyType, ElemType >, pinhao::VectorFeature< ElemType >, and pinhao::MapFeature< KeyType, ElemType >.
CompositeFeatureInfo * Feature::getCompositeFeatureInfo () const private
Casts Info to a CompositeFeatureInfo type, if possible.
Definition at line 11 of file Feature.cpp.
References Info, and isComposite().
std::string Feature::getDescription () const
Gets the description of the feature.
Definition at line 25 of file Feature.cpp.
References Info.
FeatureKind Feature::getKind () const
Returns the FeatureKind.
Definition at line 48 of file Feature.cpp.
References Kind.
std::string Feature::getName () const
Gets the name of the feature.
Definition at line 21 of file Feature.cpp.
References Info.
uint64_t Feature::getNumberOfSubFeatures () const
Gets the description of the sub-feature with name SubFeatureName.
Definition at line 43 of file Feature.cpp.
References getCompositeFeatureInfo(), pinhao::CompositeFeatureInfo::getNumberOfSubFeatures(), and isComposite().
std::string Feature::getSubFeatureDescription (std::string SubFeatureName) const
Gets the description of the sub-feature with name SubFeatureName.
Definition at line 38 of file Feature.cpp.
References getCompositeFeatureInfo(), pinhao::CompositeFeatureInfo::getSubFeatureDescription(), and hasSubFeature().
ValueType Feature::getType () const
Gets the ValueType of the feature.
Definition at line 29 of file Feature.cpp.
References Info.
bool Feature::hasSubFeature (std::string SubFeatureName) const
Returns true if there is a sub-feature with name SubFeatureName.
Definition at line 33 of file Feature.cpp.
References getCompositeFeatureInfo(), pinhao::CompositeFeatureInfo::hasSubFeature(), and isComposite().
bool Feature::isComposite () const
Returns true if the feature has more than two sub-features.
Definition at line 52 of file Feature.cpp.
References Info.
bool Feature::isDynamicFeature () const
Returns true if it is a dynamic feature.
Definition at line 72 of file Feature.cpp.
References Info.
bool Feature::isLinear () const
Returns true if it is a LinearFeature.
Definition at line 60 of file Feature.cpp.
References Kind, and pinhao::LinearKind.
bool Feature::isMapped () const
Returns true if it is a MappedFeature.
Definition at line 64 of file Feature.cpp.
References Kind, and pinhao::MappedKind.
bool Feature::isProcessed () const
Returns true if the feature has already been processed.
Definition at line 56 of file Feature.cpp.
References Processed.
bool Feature::isStaticFeature () const
Returns true if it is a static feature.
Definition at line 68 of file Feature.cpp.
References Info.
void Feature::print (std::ostream & Out = std::cout)
Prints its information into a std::ostream object in the format yaml.
Parameters
Out The output stream that the function shall print.
Definition at line 84 of file Feature.cpp.
References append().
virtual void pinhao::Feature::processModule (llvm::Module & Module) pure virtual
Gets the necessary information from a llvm::Module.
This function processes the Module in order to gather the information needed.
Parameters
Module The module to be processed.
Member Data Documentation
std::shared_ptr<FeatureInfo> pinhao::Feature::Info protected
Definition at line 42 of file Feature.h.
FeatureKind pinhao::Feature::Kind private
Definition at line 46 of file Feature.h.
bool pinhao::Feature::Processed protected
Definition at line 43 of file Feature.h.