Pinhao: pinhao::LitFormula< T > Class Template Reference
pinhao::LitFormula< T > Class Template Reference
Holds literal of the types.
#include <LitFormula.h>
Public Member Functions
void setValue (T Value)
Sets the literal value.
ValueType getType () const override
Gets the type of the Formula (what is the returning type).
FormulaKind getKind () const override
Gets a FormulaKind of this object.
void evolve (Evolution *) override
Evolves this formula, based on the Evolution algorithm.
FormulaBase * simplify () override
Simplifies the current formula.
void generate (FeatureSet *Set) override
Randomizes the generations of a Formula.
void solveFor (FeatureSet *Set) override
Evaluates the Formula for the Set.
bool operator== (const FormulaBase &Rhs) const override
bool operator< (const FormulaBase &Rhs) const override
std::unique_ptr< FormulaBase > clone () override
Clones (deep copy) the formula.
Public Member Functions inherited from pinhao::Formula< T >
virtual ~Formula ()
T & getValue ()
Gets a reference to the value.
T getValue () const
Gets a copy of the value.
virtual ValueType getOperandsType () const
Return the type of the operands. If it has none, it returns the type of the Formula.
Public Member Functions inherited from pinhao::FormulaBase
virtual ~FormulaBase ()
virtual bool isLiteral () const
Returns true if it is a Literal formula.
virtual bool isArithBinOp () const
Returns true if it is a ArithBinOp formula.
virtual bool isBoolBinOp () const
Returns true if it is a BoolBinOp formula.
virtual bool isFeature () const
Returns true if it is a Feature formula.
virtual bool isIf () const
Returns true if it is a If formula.
bool operator!= (const FormulaBase &Rhs) const
bool operator> (const FormulaBase &Rhs) const
bool operator>= (const FormulaBase &Rhs) const
bool operator<= (const FormulaBase &Rhs) const
void print (std::ostream &Out=std::cout)
Prints to an std::ostream object the information of this Formula.
Additional Inherited Members
Static Protected Member Functions inherited from pinhao::Formula< T >
static T getFormulaValue (const FormulaBase *Base)
A wrapper that gets the value yielded.
Protected Attributes inherited from pinhao::Formula< T >
T Value
The value that is yielded after evaluation.
Detailed Description
template<class T>
class pinhao::LitFormula< T >
Holds literal of the types.
Definition at line 25 of file LitFormula.h.
Member Function Documentation
template<class T > std::unique_ptr< pinhao::FormulaBase > pinhao::LitFormula< T >::clone () override virtual
Clones (deep copy) the formula.
Implements pinhao::FormulaBase.
Definition at line 102 of file LitFormula.h.
References pinhao::Formula< T >::getValue(), and pinhao::LitFormula< T >::setValue().
template<class T > void pinhao::LitFormula< T >::evolve (Evolution *) override virtual
Evolves this formula, based on the Evolution algorithm.
Implements pinhao::FormulaBase.
Definition at line 54 of file LitFormula.h.
References pinhao::Evolution::evolve(), and pinhao::Formula< T >::Value.
template<class T > void pinhao::LitFormula< T >::generate (FeatureSet * Set) override virtual
Randomizes the generations of a Formula.
Implements pinhao::FormulaBase.
Definition at line 74 of file LitFormula.h.
References pinhao::Formula< T >::Value.
template<class T > pinhao::FormulaKind pinhao::LitFormula< T >::getKind () const override virtual
Gets a FormulaKind of this object.
Implements pinhao::FormulaBase.
Definition at line 69 of file LitFormula.h.
References pinhao::Literal.
template<class T > pinhao::ValueType pinhao::LitFormula< T >::getType () const override virtual
Gets the type of the Formula (what is the returning type).
Implements pinhao::FormulaBase.
Definition at line 64 of file LitFormula.h.
template<class T > bool pinhao::LitFormula< T >::operator< (const FormulaBase & Rhs) const override virtual
Implements pinhao::FormulaBase.
Definition at line 92 of file LitFormula.h.
References pinhao::LitFormula< T >::getKind(), pinhao::FormulaBase::getKind(), pinhao::LitFormula< T >::getType(), pinhao::FormulaBase::getType(), and pinhao::Formula< T >::getValue().
template<class T > bool pinhao::LitFormula< T >::operator== (const FormulaBase & Rhs) const override virtual
Implements pinhao::FormulaBase.
Definition at line 84 of file LitFormula.h.
References pinhao::LitFormula< T >::getKind(), pinhao::FormulaBase::getKind(), pinhao::LitFormula< T >::getType(), pinhao::FormulaBase::getType(), and pinhao::Formula< T >::getValue().
template<class T > void pinhao::LitFormula< T >::setValue (T Value)
Sets the literal value.
Definition at line 49 of file LitFormula.h.
References pinhao::Formula< T >::Value.
template<class T > pinhao::FormulaBase * pinhao::LitFormula< T >::simplify () override virtual
Simplifies the current formula.
Implements pinhao::FormulaBase.
Definition at line 59 of file LitFormula.h.
template<class T > void pinhao::LitFormula< T >::solveFor (FeatureSet * Set) override virtual
Evaluates the Formula for the Set.
Implements pinhao::FormulaBase.
Definition at line 79 of file LitFormula.h.