Pinhao: SimpleEvolution Class Reference
SimpleEvolution Class Reference
Public Member Functions
SimpleEvolution (double M, FeatureSet *Set)
void mutate (std::unique_ptr< FormulaBase > *)
void evolve (std::vector< std::unique_ptr< FormulaBase > *>) override
Evolves a set of Formula's, namely the BinOpFormula and the IfFormula.
void evolve (std::pair< std::string, std::string > &) override
Evolves an FeatureFormula pair, which represents the feature and sub-feature, respectively.
void evolve (int &) override
Evolves an int value of a LitFormula<int>.
void evolve (bool &) override
Evolves an bool value of a LitFormula<bool>.
Public Member Functions inherited from pinhao::Evolution
Evolution (FeatureSet *Set)
virtual ~Evolution ()
virtual void evolve (double &Value)
Evolves an double value of a LitFormula<double>.
virtual void evolve (std::string &Value)
Evolves an string value of a LitFormula<std::string>.
Private Attributes
double M
Additional Inherited Members
Public Attributes inherited from pinhao::Evolution
FeatureSet * Set
Detailed Description
Definition at line 20 of file SimpleGrammarEvolution.cpp.
Constructor & Destructor Documentation
SimpleEvolution::SimpleEvolution (double M, FeatureSet * Set) inline
Definition at line 25 of file SimpleGrammarEvolution.cpp.
Member Function Documentation
void SimpleEvolution::evolve (std::vector< std::unique_ptr< FormulaBase > *>) override virtual
Evolves a set of Formula's, namely the BinOpFormula and the IfFormula.
Implements pinhao::Evolution.
Definition at line 39 of file SimpleGrammarEvolution.cpp.
References pinhao::UniformRandom::getRandomInt(), and pinhao::UniformRandom::getRandomReal().
void SimpleEvolution::evolve (std::pair< std::string, std::string > &) override virtual
Evolves an FeatureFormula pair, which represents the feature and sub-feature, respectively.
Implements pinhao::Evolution.
Definition at line 46 of file SimpleGrammarEvolution.cpp.
References pinhao::UniformRandom::getRandomInt().
void SimpleEvolution::evolve (int & Value) override virtual
Evolves an int value of a LitFormula<int>.
Reimplemented from pinhao::Evolution.
Definition at line 53 of file SimpleGrammarEvolution.cpp.
References pinhao::UniformRandom::getRandomInt().
void SimpleEvolution::evolve (bool & Value) override virtual
Evolves an bool value of a LitFormula<bool>.
Reimplemented from pinhao::Evolution.
Definition at line 58 of file SimpleGrammarEvolution.cpp.
void SimpleEvolution::mutate (std::unique_ptr< FormulaBase > * Form)
Definition at line 34 of file SimpleGrammarEvolution.cpp.
References pinhao::generateFormula().
Member Data Documentation
double SimpleEvolution::M private
Definition at line 22 of file SimpleGrammarEvolution.cpp.