Pinhao: pinhao Namespace Reference
pinhao Namespace Reference
Namespaces
config
Classes
class ArithmeticBinOpFormula
Represents all arithmetics operations (supported). Only numerical operands type permitted.
class BinOpFormulaBase
Base class for binary operations.
class BooleanBinOpFormula
Represents all logical operations (supported).
class CompositeFeatureInfo
This is the composite feature's information.
class Feature
This is the base class for features.
class FeatureFormula
Holds a pair of std::strings. The first represents the feature, and the second represents the sub-feature (if there is one).
class FeatureInfo
This class is the base and most simple feature information holder class.
class FeatureRegistry
This class contains all registered features as well as its manipulation methods.
class FeatureSet
This class holds all enabled features.
class FeatureSetWrapperPass
A llvm::ModulePass for the FeatureSet.
class Formula
The base template class for the Formulas.
class FormulaBase
The base class for all Formula types. A Formula is a statement which when evaluated for a FeatureSet, it yields a value.
class GEOSWrapper
This class is actually a wrapper to a set of functions of the GEOS framework.
class IfFormula
The If Formula.
class JITExecutor
Runs a given module at runtime.
class KeyIterator
Base class for iterating over the keys of some MappedFeature.
class LinearFeature
Abstract class of linear features.
class LitFormula
Holds literal of the types.
class MapFeature
This class maps a KeyType to a ElemType feature.
class MappedFeature
Abstract class of mapped features.
class MapVectorFeature
This class maps a KeyType to a vector of ElemType features.
struct OptimizationArg
An optimization argument of type ArgType.
struct OptimizationArgBase
Base class for optimization arguments.
class OptimizationInfo
class OptimizationSequence
Contains a sequence for a specific OptimizationSet.
class OptimizationSet
Holds all enabled optimizations as well as the number of repetition of each one.
class PAPIWrapper
This is a wrapper of the PAPI tool.
class RegisterFeature
Class responsible to register the new feature.
class SProfWrapper
This class is a wrapper of the StaticProfiler tool.
class StdMapKeyIterator
Concrete class that iterates over the keys of the stl provided std::map class.
class StringFeature
Implements a string version of a linear feature.
class UniformRandom
Standard random number generator wrapper.
class VectorFeature
Implements a template vector feature class.
class YAMLWrapper
This class is a wrapper class for the yaml-cpp library.
Enumerations
enum FeatureKind { FeatureKind::LinearKind, FeatureKind::MappedKind }
The kind of the feature.
enum FormulaKind {
FormulaKind::Literal = 0, FormulaKind::BooleanBinOp, FormulaKind::ArithmeticBinOp, FormulaKind::If,
FormulaKind::Feature
}
Enumeration of Formula types.
enum OperatorKind {
OperatorKind::PLUS = 0, OperatorKind::MIN, OperatorKind::MUL, OperatorKind::DIV,
OperatorKind::EQ, OperatorKind::NEQ, OperatorKind::LT, OperatorKind::GT,
OperatorKind::LEQ, OperatorKind::GEQ
}
Enumeration of the kinds of operators available.
enum Optimization {
Optimization::adce = 0, Optimization::alwaysInline, Optimization::argpromotion, Optimization::bbVectorize,
Optimization::breakCritEdges, Optimization::codegenprepare, Optimization::constmerge, Optimization::constprop,
Optimization::dce, Optimization::deadargelim, Optimization::die, Optimization::dse,
Optimization::functionattrs, Optimization::globaldce, Optimization::globalopt, Optimization::gvn,
Optimization::indvars, Optimization::inlineOpt, Optimization::instcombine, Optimization::ipconstprop,
Optimization::ipsccp, Optimization::jumpThreading, Optimization::lcssa, Optimization::licm,
Optimization::loopDeletion, Optimization::loopExtract, Optimization::loopExtractSingle, Optimization::loopReduce,
Optimization::loopRotate, Optimization::loopSimplify, Optimization::loopUnroll, Optimization::loopUnswitch,
Optimization::loweratomic, Optimization::lowerinvoke, Optimization::lowerswitch, Optimization::mem2reg,
Optimization::memcpyopt, Optimization::mergefunc, Optimization::mergereturn, Optimization::partialInliner,
Optimization::pruneEh, Optimization::reassociate, Optimization::reg2mem, Optimization::scalarrepl,
Optimization::sccp, Optimization::simplifycfg, Optimization::sink, Optimization::strip,
Optimization::stripDeadDebugInfo, Optimization::stripDeadPrototypes, Optimization::stripDebugDeclare, Optimization::stripNondebug,
Optimization::tailcallelim
}
Enumerator of the available optimizations.
enum ValueType { ValueType::Int, ValueType::Float, ValueType::Bool, ValueType::String }
Enum class to specify the type of values.
Functions
void initializeOptimizer ()
void initializeGEOSFeatures (llvm::Module &)
void initializeGEOSBasicBlockFreqFeature (llvm::Module &)
int getFormulaKindWeight (FormulaKind)
Gets the corresponding weight for the FormulaKind.
FormulaKind getFormulaKind (std::string)
Gets the corresponding FormulaKind for the std::string.
std::string getFormulaKindString (FormulaKind)
Gets the corresponding std::string for the FormulaKind.
OperatorKind getOperatorKind (std::string)
Gets the corresponding OperatorKind for the std::string.
std::string getOperatorKindString (OperatorKind)
Gets the corresponding std::string for the OperatorKind.
std::unique_ptr< FormulaBase > generateFormula (FeatureSet *, ValueType)
std::unique_ptr< FormulaBase > createLitFormula (ValueType)
Creates a LitFormula of type Type.
std::unique_ptr< FormulaBase > createArithmeticBinOpFormula (ValueType)
Creates a ArithmeticBinOpFormula whose result is of type Type.
std::unique_ptr< FormulaBase > createBooleanBinOpFormula (ValueType)
Creates a BooleanBinOpFormula whose operands are of type Type.
std::unique_ptr< FormulaBase > createIfFormula (ValueType)
Creates a IfFormula whose result is of type Type.
std::unique_ptr< FormulaBase > createFeatureFormula (ValueType)
Creates a FeatureFormula whose value is of type Type.
std::unique_ptr< FormulaBase > createFormula (FormulaKind, ValueType, ValueType=ValueType::Int)
Creates a Formula of a kind. For the BooleanBinOpFormula, the operands type must be specified.
Optimization getOptimization (std::string OptName)
Gets a Optimization corresponding to the OptName.
std::string getOptimizationName (Optimization Opt)
Gets the optimization name corresponding to the Opt.
int getPassKind (Optimization Opt)
Gets the PassKind of the Opt.
llvm::Module * applyOptimizations (llvm::Module &Module, OptimizationSet *Set)
Applies a generated OptimizationSequence to a module, from the OptimizationSet.
llvm::Module * applyOptimizations (llvm::Module &Module, OptimizationSequence *Seq)
Applies the OptimizationSequence to a module.
llvm::Module * applyOptimizations (llvm::Module &Module, std::string FunctionName, OptimizationSet *Set)
Applies a generated OptimizationSequence to a function which has name FunctionName, from the OptimizationSet.
llvm::Module * applyOptimizations (llvm::Module &Module, std::string FunctionName, OptimizationSequence *Seq)
Applies the OptimizationSequence to a function whose name is FunctionName.
llvm::Module * applyOptimizations (llvm::Module &Module, llvm::Function *Function, OptimizationSet *Set)
Applies a generated OptimizationSequence to the function Function, from the OptimizationSet.
llvm::Module * applyOptimizations (llvm::Module &Module, llvm::Function *Function, OptimizationSequence *Seq)
Applies the OptimizationSequence to a function.
template<class KType , class VType >
KeyIterator< KType > & beginKeys (Feature *F)
Wrapper function that casts some feature pointer to a MappedFeature, and returns a reference to a iterator at the beginning of the map.
template<class KType , class VType >
KeyIterator< KType > & endKeys (Feature *F)
Wrapper function that casts some feature pointer to a MappedFeature, and returns a reference to a iterator at the end of the map.
template<class T >
ValueType getValueTypeFor ()
template<>
ValueType getValueTypeFor< int > ()
template<>
ValueType getValueTypeFor< bool > ()
template<>
ValueType getValueTypeFor< double > ()
template<>
ValueType getValueTypeFor< std::string > ()
Enumeration Type Documentation
enum pinhao::FeatureKind strong
The kind of the feature.
Enumerator
LinearKind
Can get the value only by the name of the feature.
MappedKind
Needs a key in order to get the value.
Definition at line 25 of file Feature.h.
enum pinhao::FormulaKind strong
Enumeration of Formula types.
Enumerator
Literal
Literal formula.
BooleanBinOp
Logical binary operation formula.
ArithmeticBinOp
Arithmetic binary operation formula.
If
If formula.
Feature
Feature formula.
Definition at line 23 of file Formula.h.
enum pinhao::OperatorKind strong
Enumeration of the kinds of operators available.
Enumerator
PLUS
MIN
MUL
DIV
EQ
NEQ
LT
GT
LEQ
GEQ
Definition at line 55 of file Formula.h.
enum pinhao::Optimization strong
Enumerator of the available optimizations.
Enumerator
adce
alwaysInline
argpromotion
bbVectorize
breakCritEdges
codegenprepare
constmerge
constprop
dce
deadargelim
die
dse
functionattrs
globaldce
globalopt
gvn
indvars
inlineOpt
instcombine
ipconstprop
ipsccp
jumpThreading
lcssa
licm
loopDeletion
loopExtract
loopExtractSingle
loopReduce
loopRotate
loopSimplify
loopUnroll
loopUnswitch
loweratomic
lowerinvoke
lowerswitch
mem2reg
memcpyopt
mergefunc
mergereturn
partialInliner
pruneEh
reassociate
reg2mem
scalarrepl
sccp
simplifycfg
sink
strip
stripDeadDebugInfo
stripDeadPrototypes
stripDebugDeclare
stripNondebug
tailcallelim
Definition at line 24 of file Optimizations.h.
enum pinhao::ValueType strong
Enum class to specify the type of values.
Enumerator
Int
Float
Bool
String
Definition at line 17 of file Types.h.
Function Documentation
llvm::Module * pinhao::applyOptimizations (llvm::Module & Module, OptimizationSet * Set)
Applies a generated OptimizationSequence to a module, from the OptimizationSet.
Returns
The optimized module.
Definition at line 82 of file Optimizations.cpp.
References pinhao::OptimizationSet::DefaultSequence, and pinhao::OptimizationSet::generateRandomSequenceIfNone().
llvm::Module * pinhao::applyOptimizations (llvm::Module & Module, OptimizationSequence * Seq)
Applies the OptimizationSequence to a module.
Returns
The optimized module.
Definition at line 97 of file Optimizations.cpp.
References pinhao::OptimizationSequence::populatePassManager().
llvm::Module * pinhao::applyOptimizations (llvm::Module & Module, std::string FunctionName, OptimizationSet * Set)
Applies a generated OptimizationSequence to a function which has name FunctionName, from the OptimizationSet.
Returns
The optimized module.
Definition at line 92 of file Optimizations.cpp.
References applyOptimizations(), pinhao::OptimizationSet::DefaultSequence, and pinhao::OptimizationSet::generateRandomSequenceIfNone().
llvm::Module * pinhao::applyOptimizations (llvm::Module & Module, std::string FunctionName, OptimizationSequence * Seq)
Applies the OptimizationSequence to a function whose name is FunctionName.
Returns
The optimized module.
Definition at line 124 of file Optimizations.cpp.
References applyOptimizations().
llvm::Module * pinhao::applyOptimizations (llvm::Module & Module, llvm::Function * Function, OptimizationSet * Set)
Applies a generated OptimizationSequence to the function Function, from the OptimizationSet.
Returns
The optimized module.
Definition at line 87 of file Optimizations.cpp.
References applyOptimizations(), pinhao::OptimizationSet::DefaultSequence, and pinhao::OptimizationSet::generateRandomSequenceIfNone().
llvm::Module * pinhao::applyOptimizations (llvm::Module & Module, llvm::Function * Function, OptimizationSequence * Seq)
Applies the OptimizationSequence to a function.
Returns
The optimized function's module.
Definition at line 128 of file Optimizations.cpp.
References pinhao::OptimizationSequence::populateFunctionPassManager().
template<class KType , class VType > KeyIterator<KType>& pinhao::beginKeys (Feature * F)
Wrapper function that casts some feature pointer to a MappedFeature, and returns a reference to a iterator at the beginning of the map.
Definition at line 114 of file Iterator.h.
References pinhao::MappedFeature< KeyType, ValueType >::beginKeys().
std::unique_ptr< FormulaBase > pinhao::createArithmeticBinOpFormula (ValueType Type)
Creates a ArithmeticBinOpFormula whose result is of type Type.
Definition at line 59 of file Formula.cpp.
References Float, and Int.
std::unique_ptr< FormulaBase > pinhao::createBooleanBinOpFormula (ValueType Type)
Creates a BooleanBinOpFormula whose operands are of type Type.
Definition at line 70 of file Formula.cpp.
References Bool, Float, Int, and String.
std::unique_ptr< FormulaBase > pinhao::createFeatureFormula (ValueType Type)
Creates a FeatureFormula whose value is of type Type.
Definition at line 100 of file Formula.cpp.
References Bool, Float, Int, and String.
std::unique_ptr< FormulaBase > pinhao::createFormula (FormulaKind Kind, ValueType Type, ValueType OpType = ValueType::Int)
Creates a Formula of a kind. For the BooleanBinOpFormula, the operands type must be specified.
Parameters
Kind The kind of the Formula to be created.
Type The type of the Formula.
OpType The type of the operands.
Returns
A std::unique_ptr to the abstract base class (FeatureBase).
Definition at line 115 of file Formula.cpp.
References ArithmeticBinOp, Bool, BooleanBinOp, createArithmeticBinOpFormula(), createBooleanBinOpFormula(), createFeatureFormula(), createIfFormula(), createLitFormula(), Feature, getFormulaKindWeight(), pinhao::UniformRandom::getRandomInt(), If, Int, and Literal.
std::unique_ptr< FormulaBase > pinhao::createIfFormula (ValueType Type)
Creates a IfFormula whose result is of type Type.
Definition at line 85 of file Formula.cpp.
References Bool, Float, Int, and String.
std::unique_ptr< FormulaBase > pinhao::createLitFormula (ValueType Type)
Creates a LitFormula of type Type.
Definition at line 44 of file Formula.cpp.
References Bool, Float, Int, and String.
template<class KType , class VType > KeyIterator<KType>& pinhao::endKeys (Feature * F)
Wrapper function that casts some feature pointer to a MappedFeature, and returns a reference to a iterator at the end of the map.
Definition at line 124 of file Iterator.h.
References pinhao::MappedFeature< KeyType, ValueType >::endKeys().
std::unique_ptr<FormulaBase> pinhao::generateFormula (FeatureSet * , ValueType)
Definition at line 170 of file Formula.cpp.
References Bool, Float, Int, and String.
FormulaKind pinhao::getFormulaKind (std::string String)
Gets the corresponding FormulaKind for the std::string.
Definition at line 16 of file Formula.cpp.
std::string pinhao::getFormulaKindString (FormulaKind K)
Gets the corresponding std::string for the FormulaKind.
Definition at line 26 of file Formula.cpp.
int pinhao::getFormulaKindWeight (FormulaKind Kind)
Gets the corresponding weight for the FormulaKind.
Definition at line 12 of file Formula.cpp.
OperatorKind pinhao::getOperatorKind (std::string String)
Gets the corresponding OperatorKind for the std::string.
Definition at line 30 of file Formula.cpp.
std::string pinhao::getOperatorKindString (OperatorKind K)
Gets the corresponding std::string for the OperatorKind.
Definition at line 40 of file Formula.cpp.
Optimization pinhao::getOptimization (std::string OptName)
Gets a Optimization corresponding to the OptName.
Definition at line 44 of file Optimizations.cpp.
std::string pinhao::getOptimizationName (Optimization Opt)
Gets the optimization name corresponding to the Opt.
Definition at line 54 of file Optimizations.cpp.
int pinhao::getPassKind (Optimization Opt)
Gets the PassKind of the Opt.
Definition at line 58 of file Optimizations.cpp.
References getOptimizationName().
template<class T > ValueType pinhao::getValueTypeFor ()
Definition at line 25 of file Types.h.
References getValueTypeFor< bool >(), getValueTypeFor< double >(), and getValueTypeFor< int >().
template<> ValueType pinhao::getValueTypeFor< bool > ()
Definition at line 15 of file Types.cpp.
References Bool.
template<> ValueType pinhao::getValueTypeFor< double > ()
Definition at line 19 of file Types.cpp.
References Float.
template<> ValueType pinhao::getValueTypeFor< int > ()
Definition at line 11 of file Types.cpp.
References Int.
template<> ValueType pinhao::getValueTypeFor< std::string > ()
Definition at line 23 of file Types.cpp.
References String.
void pinhao::initializeGEOSBasicBlockFreqFeature (llvm::Module & Module)
Definition at line 53 of file GEOSBasicBlockFreqFeature.cpp.
References pinhao::FeatureInfo::Dynamic, pinhao::GEOSWrapper::getFrequencies(), and Int.
void pinhao::initializeGEOSFeatures (llvm::Module & Module)
Definition at line 55 of file GEOSFeatures.cpp.
References pinhao::FeatureInfo::Dynamic, Float, and pinhao::GEOSWrapper::loadCallCostFile().
void pinhao::initializeOptimizer ()
Definition at line 32 of file Optimizations.cpp.