Pinhao: std::less< pinhao::OptimizationInfo > Struct Template Reference
std::less< pinhao::OptimizationInfo > Struct Template Reference
#include <OptimizationSet.h>
Public Member Functions
template<class Type >
bool isArgLess (const pinhao::OptimizationInfo &Lhs, const pinhao::OptimizationInfo &Rhs, uint64_t I) const
bool checkArg (const pinhao::OptimizationInfo &Lhs, const pinhao::OptimizationInfo &Rhs, uint64_t I) const
bool operator() (const pinhao::OptimizationInfo &Lhs, const pinhao::OptimizationInfo &Rhs) const
Detailed Description
template<>
struct std::less< pinhao::OptimizationInfo >
Definition at line 21 of file OptimizationSet.h.
Member Function Documentation
bool std::less< pinhao::OptimizationInfo >::checkArg (const pinhao::OptimizationInfo & Lhs, const pinhao::OptimizationInfo & Rhs, uint64_t I) const inline
Definition at line 32 of file OptimizationSet.h.
References pinhao::Bool, pinhao::Float, pinhao::OptimizationInfo::getArgType(), pinhao::Int, and pinhao::String.
template<class Type > bool std::less< pinhao::OptimizationInfo >::isArgLess (const pinhao::OptimizationInfo & Lhs, const pinhao::OptimizationInfo & Rhs, uint64_t I) const inline
Definition at line 24 of file OptimizationSet.h.
References pinhao::OptimizationInfo::getArg(), and pinhao::OptimizationInfo::getNumberOfArguments().
bool std::less< pinhao::OptimizationInfo >::operator() (const pinhao::OptimizationInfo & Lhs, const pinhao::OptimizationInfo & Rhs) const inline
Definition at line 43 of file OptimizationSet.h.
References pinhao::OptimizationInfo::getNumberOfArguments(), and pinhao::OptimizationInfo::getOptimization().