Pinhao: pinhao::Candidate Struct Reference
pinhao::Candidate Struct Reference
Simple implementation of a Candidate class to be used within the GrammarEvolution algorithm.
#include <Candidate.h>
Public Member Functions
virtual ~Candidate ()
virtual void evolve (double, Evolution *)
Evolves the current candidate.
virtual void generateMissing (std::vector< DecisionPoint >, FeatureSet *)
Generate the decision point heuristics that are missing in this candidate.
Candidate * clone () const
Deep copy of this candidate.
FormulaBase *& get (uint64_t N)
Gets the Nth FormulaBase.
bool operator< (const Candidate &Rhs) const
Public Attributes
double Score
uint64_t Count
Detailed Description
Simple implementation of a Candidate class to be used within the GrammarEvolution algorithm.
Definition at line 25 of file Candidate.h.
Constructor & Destructor Documentation
pinhao::Candidate::~Candidate () virtual
Definition at line 27 of file Candidate.cpp.
Member Function Documentation
Candidate * pinhao::Candidate::clone () const
Deep copy of this candidate.
Definition at line 56 of file Candidate.cpp.
References Count, and Score.
void pinhao::Candidate::evolve (double E, Evolution * GEvo) virtual
Evolves the current candidate.
Definition at line 31 of file Candidate.cpp.
References pinhao::UniformRandom::getRandomInt(), and pinhao::simplifyFormula().
void pinhao::Candidate::generateMissing (std::vector< DecisionPoint > DPVector, FeatureSet * Set) virtual
Generate the decision point heuristics that are missing in this candidate.
Definition at line 46 of file Candidate.cpp.
References pinhao::generateFormula(), and pinhao::simplifyFormula().
FormulaBase *& pinhao::Candidate::get (uint64_t N)
Gets the Nth FormulaBase.
Definition at line 65 of file Candidate.cpp.
bool pinhao::Candidate::operator< (const Candidate & Rhs) const
Definition at line 72 of file Candidate.cpp.
Member Data Documentation
uint64_t pinhao::Candidate::Count
Definition at line 27 of file Candidate.h.
double pinhao::Candidate::Score
Definition at line 26 of file Candidate.h.